// Code generated by ent, DO NOT EDIT.

package shiftday

import (
	"back/internal/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLTE(FieldID, id))
}

// ShiftID applies equality check predicate on the "shift_id" field. It's identical to ShiftIDEQ.
func ShiftID(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldShiftID, v))
}

// Weekday applies equality check predicate on the "weekday" field. It's identical to WeekdayEQ.
func Weekday(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldWeekday, v))
}

// IsWorkingDay applies equality check predicate on the "is_working_day" field. It's identical to IsWorkingDayEQ.
func IsWorkingDay(v bool) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldIsWorkingDay, v))
}

// Mode applies equality check predicate on the "mode" field. It's identical to ModeEQ.
func Mode(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldMode, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldCreatedAt, v))
}

// ShiftIDEQ applies the EQ predicate on the "shift_id" field.
func ShiftIDEQ(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldShiftID, v))
}

// ShiftIDNEQ applies the NEQ predicate on the "shift_id" field.
func ShiftIDNEQ(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldShiftID, v))
}

// ShiftIDIn applies the In predicate on the "shift_id" field.
func ShiftIDIn(vs ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldIn(FieldShiftID, vs...))
}

// ShiftIDNotIn applies the NotIn predicate on the "shift_id" field.
func ShiftIDNotIn(vs ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNotIn(FieldShiftID, vs...))
}

// WeekdayEQ applies the EQ predicate on the "weekday" field.
func WeekdayEQ(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldWeekday, v))
}

// WeekdayNEQ applies the NEQ predicate on the "weekday" field.
func WeekdayNEQ(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldWeekday, v))
}

// WeekdayIn applies the In predicate on the "weekday" field.
func WeekdayIn(vs ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldIn(FieldWeekday, vs...))
}

// WeekdayNotIn applies the NotIn predicate on the "weekday" field.
func WeekdayNotIn(vs ...int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNotIn(FieldWeekday, vs...))
}

// WeekdayGT applies the GT predicate on the "weekday" field.
func WeekdayGT(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGT(FieldWeekday, v))
}

// WeekdayGTE applies the GTE predicate on the "weekday" field.
func WeekdayGTE(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGTE(FieldWeekday, v))
}

// WeekdayLT applies the LT predicate on the "weekday" field.
func WeekdayLT(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLT(FieldWeekday, v))
}

// WeekdayLTE applies the LTE predicate on the "weekday" field.
func WeekdayLTE(v int) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLTE(FieldWeekday, v))
}

// IsWorkingDayEQ applies the EQ predicate on the "is_working_day" field.
func IsWorkingDayEQ(v bool) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldIsWorkingDay, v))
}

// IsWorkingDayNEQ applies the NEQ predicate on the "is_working_day" field.
func IsWorkingDayNEQ(v bool) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldIsWorkingDay, v))
}

// ModeEQ applies the EQ predicate on the "mode" field.
func ModeEQ(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldMode, v))
}

// ModeNEQ applies the NEQ predicate on the "mode" field.
func ModeNEQ(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldMode, v))
}

// ModeIn applies the In predicate on the "mode" field.
func ModeIn(vs ...string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldIn(FieldMode, vs...))
}

// ModeNotIn applies the NotIn predicate on the "mode" field.
func ModeNotIn(vs ...string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNotIn(FieldMode, vs...))
}

// ModeGT applies the GT predicate on the "mode" field.
func ModeGT(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGT(FieldMode, v))
}

// ModeGTE applies the GTE predicate on the "mode" field.
func ModeGTE(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGTE(FieldMode, v))
}

// ModeLT applies the LT predicate on the "mode" field.
func ModeLT(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLT(FieldMode, v))
}

// ModeLTE applies the LTE predicate on the "mode" field.
func ModeLTE(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLTE(FieldMode, v))
}

// ModeContains applies the Contains predicate on the "mode" field.
func ModeContains(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldContains(FieldMode, v))
}

// ModeHasPrefix applies the HasPrefix predicate on the "mode" field.
func ModeHasPrefix(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldHasPrefix(FieldMode, v))
}

// ModeHasSuffix applies the HasSuffix predicate on the "mode" field.
func ModeHasSuffix(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldHasSuffix(FieldMode, v))
}

// ModeEqualFold applies the EqualFold predicate on the "mode" field.
func ModeEqualFold(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEqualFold(FieldMode, v))
}

// ModeContainsFold applies the ContainsFold predicate on the "mode" field.
func ModeContainsFold(v string) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldContainsFold(FieldMode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShiftDay {
	return predicate.ShiftDay(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShift applies the HasEdge predicate on the "shift" edge.
func HasShift() predicate.ShiftDay {
	return predicate.ShiftDay(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShiftTable, ShiftColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShiftWith applies the HasEdge predicate on the "shift" edge with a given conditions (other predicates).
func HasShiftWith(preds ...predicate.Shift) predicate.ShiftDay {
	return predicate.ShiftDay(func(s *sql.Selector) {
		step := newShiftStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShiftDay) predicate.ShiftDay {
	return predicate.ShiftDay(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShiftDay) predicate.ShiftDay {
	return predicate.ShiftDay(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShiftDay) predicate.ShiftDay {
	return predicate.ShiftDay(sql.NotPredicates(p))
}
