// Code generated by ent, DO NOT EDIT.

package branchaddress

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the branchaddress type in the database.
	Label = "branch_address"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBranchID holds the string denoting the branch_id field in the database.
	FieldBranchID = "branch_id"
	// FieldCommuneID holds the string denoting the commune_id field in the database.
	FieldCommuneID = "commune_id"
	// FieldStreet holds the string denoting the street field in the database.
	FieldStreet = "street"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldApartment holds the string denoting the apartment field in the database.
	FieldApartment = "apartment"
	// FieldExtra holds the string denoting the extra field in the database.
	FieldExtra = "extra"
	// EdgeBranch holds the string denoting the branch edge name in mutations.
	EdgeBranch = "branch"
	// EdgeCommune holds the string denoting the commune edge name in mutations.
	EdgeCommune = "commune"
	// Table holds the table name of the branchaddress in the database.
	Table = "branch_addresses"
	// BranchTable is the table that holds the branch relation/edge.
	BranchTable = "branch_addresses"
	// BranchInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchInverseTable = "branches"
	// BranchColumn is the table column denoting the branch relation/edge.
	BranchColumn = "branch_id"
	// CommuneTable is the table that holds the commune relation/edge.
	CommuneTable = "branch_addresses"
	// CommuneInverseTable is the table name for the Commune entity.
	// It exists in this package in order to avoid circular dependency with the "commune" package.
	CommuneInverseTable = "communes"
	// CommuneColumn is the table column denoting the commune relation/edge.
	CommuneColumn = "commune_id"
)

// Columns holds all SQL columns for branchaddress fields.
var Columns = []string{
	FieldID,
	FieldBranchID,
	FieldCommuneID,
	FieldStreet,
	FieldNumber,
	FieldApartment,
	FieldExtra,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// StreetValidator is a validator for the "street" field. It is called by the builders before save.
	StreetValidator func(string) error
	// NumberValidator is a validator for the "number" field. It is called by the builders before save.
	NumberValidator func(string) error
)

// OrderOption defines the ordering options for the BranchAddress queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBranchID orders the results by the branch_id field.
func ByBranchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBranchID, opts...).ToFunc()
}

// ByCommuneID orders the results by the commune_id field.
func ByCommuneID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommuneID, opts...).ToFunc()
}

// ByStreet orders the results by the street field.
func ByStreet(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStreet, opts...).ToFunc()
}

// ByNumber orders the results by the number field.
func ByNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumber, opts...).ToFunc()
}

// ByApartment orders the results by the apartment field.
func ByApartment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApartment, opts...).ToFunc()
}

// ByExtra orders the results by the extra field.
func ByExtra(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtra, opts...).ToFunc()
}

// ByBranchField orders the results by branch field.
func ByBranchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBranchStep(), sql.OrderByField(field, opts...))
	}
}

// ByCommuneField orders the results by commune field.
func ByCommuneField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommuneStep(), sql.OrderByField(field, opts...))
	}
}
func newBranchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BranchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, BranchTable, BranchColumn),
	)
}
func newCommuneStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommuneInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CommuneTable, CommuneColumn),
	)
}
