// Code generated by ent, DO NOT EDIT.

package attendanceday

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the attendanceday type in the database.
	Label = "attendance_day"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldBranchID holds the string denoting the branch_id field in the database.
	FieldBranchID = "branch_id"
	// FieldAccessPointID holds the string denoting the access_point_id field in the database.
	FieldAccessPointID = "access_point_id"
	// FieldWorkDate holds the string denoting the work_date field in the database.
	FieldWorkDate = "work_date"
	// FieldWorkInAt holds the string denoting the work_in_at field in the database.
	FieldWorkInAt = "work_in_at"
	// FieldBreakOutAt holds the string denoting the break_out_at field in the database.
	FieldBreakOutAt = "break_out_at"
	// FieldBreakInAt holds the string denoting the break_in_at field in the database.
	FieldBreakInAt = "break_in_at"
	// FieldWorkOutAt holds the string denoting the work_out_at field in the database.
	FieldWorkOutAt = "work_out_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeBranch holds the string denoting the branch edge name in mutations.
	EdgeBranch = "branch"
	// EdgeAccessPoint holds the string denoting the access_point edge name in mutations.
	EdgeAccessPoint = "access_point"
	// Table holds the table name of the attendanceday in the database.
	Table = "attendance_days"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "attendance_days"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// BranchTable is the table that holds the branch relation/edge.
	BranchTable = "attendance_days"
	// BranchInverseTable is the table name for the Branch entity.
	// It exists in this package in order to avoid circular dependency with the "branch" package.
	BranchInverseTable = "branches"
	// BranchColumn is the table column denoting the branch relation/edge.
	BranchColumn = "branch_id"
	// AccessPointTable is the table that holds the access_point relation/edge.
	AccessPointTable = "attendance_days"
	// AccessPointInverseTable is the table name for the AccessPoint entity.
	// It exists in this package in order to avoid circular dependency with the "accesspoint" package.
	AccessPointInverseTable = "access_points"
	// AccessPointColumn is the table column denoting the access_point relation/edge.
	AccessPointColumn = "access_point_id"
)

// Columns holds all SQL columns for attendanceday fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldBranchID,
	FieldAccessPointID,
	FieldWorkDate,
	FieldWorkInAt,
	FieldBreakOutAt,
	FieldBreakInAt,
	FieldWorkOutAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "attendance_days"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"access_point_attendance_days",
	"user_attendance_days",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AttendanceDay queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByBranchID orders the results by the branch_id field.
func ByBranchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBranchID, opts...).ToFunc()
}

// ByAccessPointID orders the results by the access_point_id field.
func ByAccessPointID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessPointID, opts...).ToFunc()
}

// ByWorkDate orders the results by the work_date field.
func ByWorkDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkDate, opts...).ToFunc()
}

// ByWorkInAt orders the results by the work_in_at field.
func ByWorkInAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkInAt, opts...).ToFunc()
}

// ByBreakOutAt orders the results by the break_out_at field.
func ByBreakOutAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBreakOutAt, opts...).ToFunc()
}

// ByBreakInAt orders the results by the break_in_at field.
func ByBreakInAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBreakInAt, opts...).ToFunc()
}

// ByWorkOutAt orders the results by the work_out_at field.
func ByWorkOutAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkOutAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByBranchField orders the results by branch field.
func ByBranchField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBranchStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccessPointField orders the results by access_point field.
func ByAccessPointField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccessPointStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newBranchStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BranchInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, BranchTable, BranchColumn),
	)
}
func newAccessPointStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccessPointInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AccessPointTable, AccessPointColumn),
	)
}
