// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/accesspoint"
	"back/internal/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessPointDelete is the builder for deleting a AccessPoint entity.
type AccessPointDelete struct {
	config
	hooks    []Hook
	mutation *AccessPointMutation
}

// Where appends a list predicates to the AccessPointDelete builder.
func (_d *AccessPointDelete) Where(ps ...predicate.AccessPoint) *AccessPointDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccessPointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessPointDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccessPointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accesspoint.Table, sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccessPointDeleteOne is the builder for deleting a single AccessPoint entity.
type AccessPointDeleteOne struct {
	_d *AccessPointDelete
}

// Where appends a list predicates to the AccessPointDelete builder.
func (_d *AccessPointDeleteOne) Where(ps ...predicate.AccessPoint) *AccessPointDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccessPointDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accesspoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccessPointDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
