// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/accesspoint"
	"back/internal/ent/attendanceday"
	"back/internal/ent/branch"
	"back/internal/ent/predicate"
	"back/internal/ent/useraccesspoint"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AccessPointQuery is the builder for querying AccessPoint entities.
type AccessPointQuery struct {
	config
	ctx                  *QueryContext
	order                []accesspoint.OrderOption
	inters               []Interceptor
	predicates           []predicate.AccessPoint
	withBranch           *BranchQuery
	withUserAccessPoints *UserAccessPointQuery
	withAttendanceDays   *AttendanceDayQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AccessPointQuery builder.
func (_q *AccessPointQuery) Where(ps ...predicate.AccessPoint) *AccessPointQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AccessPointQuery) Limit(limit int) *AccessPointQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AccessPointQuery) Offset(offset int) *AccessPointQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AccessPointQuery) Unique(unique bool) *AccessPointQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AccessPointQuery) Order(o ...accesspoint.OrderOption) *AccessPointQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryBranch chains the current query on the "branch" edge.
func (_q *AccessPointQuery) QueryBranch() *BranchQuery {
	query := (&BranchClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesspoint.Table, accesspoint.FieldID, selector),
			sqlgraph.To(branch.Table, branch.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, accesspoint.BranchTable, accesspoint.BranchColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUserAccessPoints chains the current query on the "user_access_points" edge.
func (_q *AccessPointQuery) QueryUserAccessPoints() *UserAccessPointQuery {
	query := (&UserAccessPointClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesspoint.Table, accesspoint.FieldID, selector),
			sqlgraph.To(useraccesspoint.Table, useraccesspoint.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesspoint.UserAccessPointsTable, accesspoint.UserAccessPointsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAttendanceDays chains the current query on the "attendance_days" edge.
func (_q *AccessPointQuery) QueryAttendanceDays() *AttendanceDayQuery {
	query := (&AttendanceDayClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(accesspoint.Table, accesspoint.FieldID, selector),
			sqlgraph.To(attendanceday.Table, attendanceday.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, accesspoint.AttendanceDaysTable, accesspoint.AttendanceDaysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AccessPoint entity from the query.
// Returns a *NotFoundError when no AccessPoint was found.
func (_q *AccessPointQuery) First(ctx context.Context) (*AccessPoint, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{accesspoint.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AccessPointQuery) FirstX(ctx context.Context) *AccessPoint {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AccessPoint ID from the query.
// Returns a *NotFoundError when no AccessPoint ID was found.
func (_q *AccessPointQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{accesspoint.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AccessPointQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AccessPoint entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AccessPoint entity is found.
// Returns a *NotFoundError when no AccessPoint entities are found.
func (_q *AccessPointQuery) Only(ctx context.Context) (*AccessPoint, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{accesspoint.Label}
	default:
		return nil, &NotSingularError{accesspoint.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AccessPointQuery) OnlyX(ctx context.Context) *AccessPoint {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AccessPoint ID in the query.
// Returns a *NotSingularError when more than one AccessPoint ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AccessPointQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{accesspoint.Label}
	default:
		err = &NotSingularError{accesspoint.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AccessPointQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AccessPoints.
func (_q *AccessPointQuery) All(ctx context.Context) ([]*AccessPoint, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AccessPoint, *AccessPointQuery]()
	return withInterceptors[[]*AccessPoint](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AccessPointQuery) AllX(ctx context.Context) []*AccessPoint {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AccessPoint IDs.
func (_q *AccessPointQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(accesspoint.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AccessPointQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AccessPointQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AccessPointQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AccessPointQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AccessPointQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AccessPointQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AccessPointQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AccessPointQuery) Clone() *AccessPointQuery {
	if _q == nil {
		return nil
	}
	return &AccessPointQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]accesspoint.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.AccessPoint{}, _q.predicates...),
		withBranch:           _q.withBranch.Clone(),
		withUserAccessPoints: _q.withUserAccessPoints.Clone(),
		withAttendanceDays:   _q.withAttendanceDays.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithBranch tells the query-builder to eager-load the nodes that are connected to
// the "branch" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessPointQuery) WithBranch(opts ...func(*BranchQuery)) *AccessPointQuery {
	query := (&BranchClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBranch = query
	return _q
}

// WithUserAccessPoints tells the query-builder to eager-load the nodes that are connected to
// the "user_access_points" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessPointQuery) WithUserAccessPoints(opts ...func(*UserAccessPointQuery)) *AccessPointQuery {
	query := (&UserAccessPointClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUserAccessPoints = query
	return _q
}

// WithAttendanceDays tells the query-builder to eager-load the nodes that are connected to
// the "attendance_days" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AccessPointQuery) WithAttendanceDays(opts ...func(*AttendanceDayQuery)) *AccessPointQuery {
	query := (&AttendanceDayClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAttendanceDays = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		BranchID int `json:"branch_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AccessPoint.Query().
//		GroupBy(accesspoint.FieldBranchID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *AccessPointQuery) GroupBy(field string, fields ...string) *AccessPointGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AccessPointGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = accesspoint.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		BranchID int `json:"branch_id,omitempty"`
//	}
//
//	client.AccessPoint.Query().
//		Select(accesspoint.FieldBranchID).
//		Scan(ctx, &v)
func (_q *AccessPointQuery) Select(fields ...string) *AccessPointSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AccessPointSelect{AccessPointQuery: _q}
	sbuild.label = accesspoint.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AccessPointSelect configured with the given aggregations.
func (_q *AccessPointQuery) Aggregate(fns ...AggregateFunc) *AccessPointSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AccessPointQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !accesspoint.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AccessPointQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AccessPoint, error) {
	var (
		nodes       = []*AccessPoint{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withBranch != nil,
			_q.withUserAccessPoints != nil,
			_q.withAttendanceDays != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AccessPoint).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AccessPoint{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withBranch; query != nil {
		if err := _q.loadBranch(ctx, query, nodes, nil,
			func(n *AccessPoint, e *Branch) { n.Edges.Branch = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUserAccessPoints; query != nil {
		if err := _q.loadUserAccessPoints(ctx, query, nodes,
			func(n *AccessPoint) { n.Edges.UserAccessPoints = []*UserAccessPoint{} },
			func(n *AccessPoint, e *UserAccessPoint) {
				n.Edges.UserAccessPoints = append(n.Edges.UserAccessPoints, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withAttendanceDays; query != nil {
		if err := _q.loadAttendanceDays(ctx, query, nodes,
			func(n *AccessPoint) { n.Edges.AttendanceDays = []*AttendanceDay{} },
			func(n *AccessPoint, e *AttendanceDay) { n.Edges.AttendanceDays = append(n.Edges.AttendanceDays, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AccessPointQuery) loadBranch(ctx context.Context, query *BranchQuery, nodes []*AccessPoint, init func(*AccessPoint), assign func(*AccessPoint, *Branch)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AccessPoint)
	for i := range nodes {
		fk := nodes[i].BranchID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(branch.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "branch_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *AccessPointQuery) loadUserAccessPoints(ctx context.Context, query *UserAccessPointQuery, nodes []*AccessPoint, init func(*AccessPoint), assign func(*AccessPoint, *UserAccessPoint)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessPoint)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(useraccesspoint.FieldAccessPointID)
	}
	query.Where(predicate.UserAccessPoint(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesspoint.UserAccessPointsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AccessPointID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_point_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AccessPointQuery) loadAttendanceDays(ctx context.Context, query *AttendanceDayQuery, nodes []*AccessPoint, init func(*AccessPoint), assign func(*AccessPoint, *AttendanceDay)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*AccessPoint)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.AttendanceDay(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(accesspoint.AttendanceDaysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.access_point_attendance_days
		if fk == nil {
			return fmt.Errorf(`foreign-key "access_point_attendance_days" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "access_point_attendance_days" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AccessPointQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AccessPointQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(accesspoint.Table, accesspoint.Columns, sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accesspoint.FieldID)
		for i := range fields {
			if fields[i] != accesspoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withBranch != nil {
			_spec.Node.AddColumnOnce(accesspoint.FieldBranchID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AccessPointQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(accesspoint.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = accesspoint.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AccessPointGroupBy is the group-by builder for AccessPoint entities.
type AccessPointGroupBy struct {
	selector
	build *AccessPointQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AccessPointGroupBy) Aggregate(fns ...AggregateFunc) *AccessPointGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AccessPointGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessPointQuery, *AccessPointGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AccessPointGroupBy) sqlScan(ctx context.Context, root *AccessPointQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AccessPointSelect is the builder for selecting fields of AccessPoint entities.
type AccessPointSelect struct {
	*AccessPointQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AccessPointSelect) Aggregate(fns ...AggregateFunc) *AccessPointSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AccessPointSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AccessPointQuery, *AccessPointSelect](ctx, _s.AccessPointQuery, _s, _s.inters, v)
}

func (_s *AccessPointSelect) sqlScan(ctx context.Context, root *AccessPointQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
