// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/accesspoint"
	"back/internal/ent/attendanceday"
	"back/internal/ent/branch"
	"back/internal/ent/predicate"
	"back/internal/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AttendanceDayUpdate is the builder for updating AttendanceDay entities.
type AttendanceDayUpdate struct {
	config
	hooks    []Hook
	mutation *AttendanceDayMutation
}

// Where appends a list predicates to the AttendanceDayUpdate builder.
func (_u *AttendanceDayUpdate) Where(ps ...predicate.AttendanceDay) *AttendanceDayUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AttendanceDayUpdate) SetUserID(v int) *AttendanceDayUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableUserID(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *AttendanceDayUpdate) SetBranchID(v int) *AttendanceDayUpdate {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableBranchID(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *AttendanceDayUpdate) SetAccessPointID(v int) *AttendanceDayUpdate {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableAccessPointID(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// ClearAccessPointID clears the value of the "access_point_id" field.
func (_u *AttendanceDayUpdate) ClearAccessPointID() *AttendanceDayUpdate {
	_u.mutation.ClearAccessPointID()
	return _u
}

// SetWorkDate sets the "work_date" field.
func (_u *AttendanceDayUpdate) SetWorkDate(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetWorkDate(v)
	return _u
}

// SetNillableWorkDate sets the "work_date" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableWorkDate(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetWorkDate(*v)
	}
	return _u
}

// SetWorkInAt sets the "work_in_at" field.
func (_u *AttendanceDayUpdate) SetWorkInAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetWorkInAt(v)
	return _u
}

// SetNillableWorkInAt sets the "work_in_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableWorkInAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetWorkInAt(*v)
	}
	return _u
}

// ClearWorkInAt clears the value of the "work_in_at" field.
func (_u *AttendanceDayUpdate) ClearWorkInAt() *AttendanceDayUpdate {
	_u.mutation.ClearWorkInAt()
	return _u
}

// SetBreakOutAt sets the "break_out_at" field.
func (_u *AttendanceDayUpdate) SetBreakOutAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetBreakOutAt(v)
	return _u
}

// SetNillableBreakOutAt sets the "break_out_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableBreakOutAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetBreakOutAt(*v)
	}
	return _u
}

// ClearBreakOutAt clears the value of the "break_out_at" field.
func (_u *AttendanceDayUpdate) ClearBreakOutAt() *AttendanceDayUpdate {
	_u.mutation.ClearBreakOutAt()
	return _u
}

// SetBreakInAt sets the "break_in_at" field.
func (_u *AttendanceDayUpdate) SetBreakInAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetBreakInAt(v)
	return _u
}

// SetNillableBreakInAt sets the "break_in_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableBreakInAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetBreakInAt(*v)
	}
	return _u
}

// ClearBreakInAt clears the value of the "break_in_at" field.
func (_u *AttendanceDayUpdate) ClearBreakInAt() *AttendanceDayUpdate {
	_u.mutation.ClearBreakInAt()
	return _u
}

// SetWorkOutAt sets the "work_out_at" field.
func (_u *AttendanceDayUpdate) SetWorkOutAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetWorkOutAt(v)
	return _u
}

// SetNillableWorkOutAt sets the "work_out_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableWorkOutAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetWorkOutAt(*v)
	}
	return _u
}

// ClearWorkOutAt clears the value of the "work_out_at" field.
func (_u *AttendanceDayUpdate) ClearWorkOutAt() *AttendanceDayUpdate {
	_u.mutation.ClearWorkOutAt()
	return _u
}

// SetLateMinutes sets the "late_minutes" field.
func (_u *AttendanceDayUpdate) SetLateMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.ResetLateMinutes()
	_u.mutation.SetLateMinutes(v)
	return _u
}

// SetNillableLateMinutes sets the "late_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableLateMinutes(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetLateMinutes(*v)
	}
	return _u
}

// AddLateMinutes adds value to the "late_minutes" field.
func (_u *AttendanceDayUpdate) AddLateMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.AddLateMinutes(v)
	return _u
}

// ClearLateMinutes clears the value of the "late_minutes" field.
func (_u *AttendanceDayUpdate) ClearLateMinutes() *AttendanceDayUpdate {
	_u.mutation.ClearLateMinutes()
	return _u
}

// SetOvertimeMinutes sets the "overtime_minutes" field.
func (_u *AttendanceDayUpdate) SetOvertimeMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.ResetOvertimeMinutes()
	_u.mutation.SetOvertimeMinutes(v)
	return _u
}

// SetNillableOvertimeMinutes sets the "overtime_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableOvertimeMinutes(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetOvertimeMinutes(*v)
	}
	return _u
}

// AddOvertimeMinutes adds value to the "overtime_minutes" field.
func (_u *AttendanceDayUpdate) AddOvertimeMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.AddOvertimeMinutes(v)
	return _u
}

// ClearOvertimeMinutes clears the value of the "overtime_minutes" field.
func (_u *AttendanceDayUpdate) ClearOvertimeMinutes() *AttendanceDayUpdate {
	_u.mutation.ClearOvertimeMinutes()
	return _u
}

// SetEarlyExitMinutes sets the "early_exit_minutes" field.
func (_u *AttendanceDayUpdate) SetEarlyExitMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.ResetEarlyExitMinutes()
	_u.mutation.SetEarlyExitMinutes(v)
	return _u
}

// SetNillableEarlyExitMinutes sets the "early_exit_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableEarlyExitMinutes(v *int) *AttendanceDayUpdate {
	if v != nil {
		_u.SetEarlyExitMinutes(*v)
	}
	return _u
}

// AddEarlyExitMinutes adds value to the "early_exit_minutes" field.
func (_u *AttendanceDayUpdate) AddEarlyExitMinutes(v int) *AttendanceDayUpdate {
	_u.mutation.AddEarlyExitMinutes(v)
	return _u
}

// ClearEarlyExitMinutes clears the value of the "early_exit_minutes" field.
func (_u *AttendanceDayUpdate) ClearEarlyExitMinutes() *AttendanceDayUpdate {
	_u.mutation.ClearEarlyExitMinutes()
	return _u
}

// SetEdited sets the "edited" field.
func (_u *AttendanceDayUpdate) SetEdited(v bool) *AttendanceDayUpdate {
	_u.mutation.SetEdited(v)
	return _u
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableEdited(v *bool) *AttendanceDayUpdate {
	if v != nil {
		_u.SetEdited(*v)
	}
	return _u
}

// SetLastEditReason sets the "last_edit_reason" field.
func (_u *AttendanceDayUpdate) SetLastEditReason(v string) *AttendanceDayUpdate {
	_u.mutation.SetLastEditReason(v)
	return _u
}

// SetNillableLastEditReason sets the "last_edit_reason" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableLastEditReason(v *string) *AttendanceDayUpdate {
	if v != nil {
		_u.SetLastEditReason(*v)
	}
	return _u
}

// ClearLastEditReason clears the value of the "last_edit_reason" field.
func (_u *AttendanceDayUpdate) ClearLastEditReason() *AttendanceDayUpdate {
	_u.mutation.ClearLastEditReason()
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *AttendanceDayUpdate) SetEditedAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableEditedAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *AttendanceDayUpdate) ClearEditedAt() *AttendanceDayUpdate {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AttendanceDayUpdate) SetCreatedAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AttendanceDayUpdate) SetNillableCreatedAt(v *time.Time) *AttendanceDayUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AttendanceDayUpdate) SetUpdatedAt(v time.Time) *AttendanceDayUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttendanceDayUpdate) SetUser(v *User) *AttendanceDayUpdate {
	return _u.SetUserID(v.ID)
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *AttendanceDayUpdate) SetBranch(v *Branch) *AttendanceDayUpdate {
	return _u.SetBranchID(v.ID)
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *AttendanceDayUpdate) SetAccessPoint(v *AccessPoint) *AttendanceDayUpdate {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the AttendanceDayMutation object of the builder.
func (_u *AttendanceDayUpdate) Mutation() *AttendanceDayMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttendanceDayUpdate) ClearUser() *AttendanceDayUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *AttendanceDayUpdate) ClearBranch() *AttendanceDayUpdate {
	_u.mutation.ClearBranch()
	return _u
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *AttendanceDayUpdate) ClearAccessPoint() *AttendanceDayUpdate {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AttendanceDayUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttendanceDayUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AttendanceDayUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttendanceDayUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AttendanceDayUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := attendanceday.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttendanceDayUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttendanceDay.user"`)
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttendanceDay.branch"`)
	}
	return nil
}

func (_u *AttendanceDayUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attendanceday.Table, attendanceday.Columns, sqlgraph.NewFieldSpec(attendanceday.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkDate(); ok {
		_spec.SetField(attendanceday.FieldWorkDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkInAt(); ok {
		_spec.SetField(attendanceday.FieldWorkInAt, field.TypeTime, value)
	}
	if _u.mutation.WorkInAtCleared() {
		_spec.ClearField(attendanceday.FieldWorkInAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreakOutAt(); ok {
		_spec.SetField(attendanceday.FieldBreakOutAt, field.TypeTime, value)
	}
	if _u.mutation.BreakOutAtCleared() {
		_spec.ClearField(attendanceday.FieldBreakOutAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreakInAt(); ok {
		_spec.SetField(attendanceday.FieldBreakInAt, field.TypeTime, value)
	}
	if _u.mutation.BreakInAtCleared() {
		_spec.ClearField(attendanceday.FieldBreakInAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkOutAt(); ok {
		_spec.SetField(attendanceday.FieldWorkOutAt, field.TypeTime, value)
	}
	if _u.mutation.WorkOutAtCleared() {
		_spec.ClearField(attendanceday.FieldWorkOutAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LateMinutes(); ok {
		_spec.SetField(attendanceday.FieldLateMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLateMinutes(); ok {
		_spec.AddField(attendanceday.FieldLateMinutes, field.TypeInt, value)
	}
	if _u.mutation.LateMinutesCleared() {
		_spec.ClearField(attendanceday.FieldLateMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.OvertimeMinutes(); ok {
		_spec.SetField(attendanceday.FieldOvertimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOvertimeMinutes(); ok {
		_spec.AddField(attendanceday.FieldOvertimeMinutes, field.TypeInt, value)
	}
	if _u.mutation.OvertimeMinutesCleared() {
		_spec.ClearField(attendanceday.FieldOvertimeMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.EarlyExitMinutes(); ok {
		_spec.SetField(attendanceday.FieldEarlyExitMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarlyExitMinutes(); ok {
		_spec.AddField(attendanceday.FieldEarlyExitMinutes, field.TypeInt, value)
	}
	if _u.mutation.EarlyExitMinutesCleared() {
		_spec.ClearField(attendanceday.FieldEarlyExitMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.Edited(); ok {
		_spec.SetField(attendanceday.FieldEdited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastEditReason(); ok {
		_spec.SetField(attendanceday.FieldLastEditReason, field.TypeString, value)
	}
	if _u.mutation.LastEditReasonCleared() {
		_spec.ClearField(attendanceday.FieldLastEditReason, field.TypeString)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(attendanceday.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(attendanceday.FieldEditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(attendanceday.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(attendanceday.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.UserTable,
			Columns: []string{attendanceday.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.UserTable,
			Columns: []string{attendanceday.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.BranchTable,
			Columns: []string{attendanceday.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.BranchTable,
			Columns: []string{attendanceday.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.AccessPointTable,
			Columns: []string{attendanceday.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.AccessPointTable,
			Columns: []string{attendanceday.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attendanceday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AttendanceDayUpdateOne is the builder for updating a single AttendanceDay entity.
type AttendanceDayUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AttendanceDayMutation
}

// SetUserID sets the "user_id" field.
func (_u *AttendanceDayUpdateOne) SetUserID(v int) *AttendanceDayUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableUserID(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *AttendanceDayUpdateOne) SetBranchID(v int) *AttendanceDayUpdateOne {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableBranchID(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *AttendanceDayUpdateOne) SetAccessPointID(v int) *AttendanceDayUpdateOne {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableAccessPointID(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// ClearAccessPointID clears the value of the "access_point_id" field.
func (_u *AttendanceDayUpdateOne) ClearAccessPointID() *AttendanceDayUpdateOne {
	_u.mutation.ClearAccessPointID()
	return _u
}

// SetWorkDate sets the "work_date" field.
func (_u *AttendanceDayUpdateOne) SetWorkDate(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetWorkDate(v)
	return _u
}

// SetNillableWorkDate sets the "work_date" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableWorkDate(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetWorkDate(*v)
	}
	return _u
}

// SetWorkInAt sets the "work_in_at" field.
func (_u *AttendanceDayUpdateOne) SetWorkInAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetWorkInAt(v)
	return _u
}

// SetNillableWorkInAt sets the "work_in_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableWorkInAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetWorkInAt(*v)
	}
	return _u
}

// ClearWorkInAt clears the value of the "work_in_at" field.
func (_u *AttendanceDayUpdateOne) ClearWorkInAt() *AttendanceDayUpdateOne {
	_u.mutation.ClearWorkInAt()
	return _u
}

// SetBreakOutAt sets the "break_out_at" field.
func (_u *AttendanceDayUpdateOne) SetBreakOutAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetBreakOutAt(v)
	return _u
}

// SetNillableBreakOutAt sets the "break_out_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableBreakOutAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetBreakOutAt(*v)
	}
	return _u
}

// ClearBreakOutAt clears the value of the "break_out_at" field.
func (_u *AttendanceDayUpdateOne) ClearBreakOutAt() *AttendanceDayUpdateOne {
	_u.mutation.ClearBreakOutAt()
	return _u
}

// SetBreakInAt sets the "break_in_at" field.
func (_u *AttendanceDayUpdateOne) SetBreakInAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetBreakInAt(v)
	return _u
}

// SetNillableBreakInAt sets the "break_in_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableBreakInAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetBreakInAt(*v)
	}
	return _u
}

// ClearBreakInAt clears the value of the "break_in_at" field.
func (_u *AttendanceDayUpdateOne) ClearBreakInAt() *AttendanceDayUpdateOne {
	_u.mutation.ClearBreakInAt()
	return _u
}

// SetWorkOutAt sets the "work_out_at" field.
func (_u *AttendanceDayUpdateOne) SetWorkOutAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetWorkOutAt(v)
	return _u
}

// SetNillableWorkOutAt sets the "work_out_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableWorkOutAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetWorkOutAt(*v)
	}
	return _u
}

// ClearWorkOutAt clears the value of the "work_out_at" field.
func (_u *AttendanceDayUpdateOne) ClearWorkOutAt() *AttendanceDayUpdateOne {
	_u.mutation.ClearWorkOutAt()
	return _u
}

// SetLateMinutes sets the "late_minutes" field.
func (_u *AttendanceDayUpdateOne) SetLateMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.ResetLateMinutes()
	_u.mutation.SetLateMinutes(v)
	return _u
}

// SetNillableLateMinutes sets the "late_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableLateMinutes(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetLateMinutes(*v)
	}
	return _u
}

// AddLateMinutes adds value to the "late_minutes" field.
func (_u *AttendanceDayUpdateOne) AddLateMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.AddLateMinutes(v)
	return _u
}

// ClearLateMinutes clears the value of the "late_minutes" field.
func (_u *AttendanceDayUpdateOne) ClearLateMinutes() *AttendanceDayUpdateOne {
	_u.mutation.ClearLateMinutes()
	return _u
}

// SetOvertimeMinutes sets the "overtime_minutes" field.
func (_u *AttendanceDayUpdateOne) SetOvertimeMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.ResetOvertimeMinutes()
	_u.mutation.SetOvertimeMinutes(v)
	return _u
}

// SetNillableOvertimeMinutes sets the "overtime_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableOvertimeMinutes(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetOvertimeMinutes(*v)
	}
	return _u
}

// AddOvertimeMinutes adds value to the "overtime_minutes" field.
func (_u *AttendanceDayUpdateOne) AddOvertimeMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.AddOvertimeMinutes(v)
	return _u
}

// ClearOvertimeMinutes clears the value of the "overtime_minutes" field.
func (_u *AttendanceDayUpdateOne) ClearOvertimeMinutes() *AttendanceDayUpdateOne {
	_u.mutation.ClearOvertimeMinutes()
	return _u
}

// SetEarlyExitMinutes sets the "early_exit_minutes" field.
func (_u *AttendanceDayUpdateOne) SetEarlyExitMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.ResetEarlyExitMinutes()
	_u.mutation.SetEarlyExitMinutes(v)
	return _u
}

// SetNillableEarlyExitMinutes sets the "early_exit_minutes" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableEarlyExitMinutes(v *int) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetEarlyExitMinutes(*v)
	}
	return _u
}

// AddEarlyExitMinutes adds value to the "early_exit_minutes" field.
func (_u *AttendanceDayUpdateOne) AddEarlyExitMinutes(v int) *AttendanceDayUpdateOne {
	_u.mutation.AddEarlyExitMinutes(v)
	return _u
}

// ClearEarlyExitMinutes clears the value of the "early_exit_minutes" field.
func (_u *AttendanceDayUpdateOne) ClearEarlyExitMinutes() *AttendanceDayUpdateOne {
	_u.mutation.ClearEarlyExitMinutes()
	return _u
}

// SetEdited sets the "edited" field.
func (_u *AttendanceDayUpdateOne) SetEdited(v bool) *AttendanceDayUpdateOne {
	_u.mutation.SetEdited(v)
	return _u
}

// SetNillableEdited sets the "edited" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableEdited(v *bool) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetEdited(*v)
	}
	return _u
}

// SetLastEditReason sets the "last_edit_reason" field.
func (_u *AttendanceDayUpdateOne) SetLastEditReason(v string) *AttendanceDayUpdateOne {
	_u.mutation.SetLastEditReason(v)
	return _u
}

// SetNillableLastEditReason sets the "last_edit_reason" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableLastEditReason(v *string) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetLastEditReason(*v)
	}
	return _u
}

// ClearLastEditReason clears the value of the "last_edit_reason" field.
func (_u *AttendanceDayUpdateOne) ClearLastEditReason() *AttendanceDayUpdateOne {
	_u.mutation.ClearLastEditReason()
	return _u
}

// SetEditedAt sets the "edited_at" field.
func (_u *AttendanceDayUpdateOne) SetEditedAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetEditedAt(v)
	return _u
}

// SetNillableEditedAt sets the "edited_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableEditedAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetEditedAt(*v)
	}
	return _u
}

// ClearEditedAt clears the value of the "edited_at" field.
func (_u *AttendanceDayUpdateOne) ClearEditedAt() *AttendanceDayUpdateOne {
	_u.mutation.ClearEditedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AttendanceDayUpdateOne) SetCreatedAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AttendanceDayUpdateOne) SetNillableCreatedAt(v *time.Time) *AttendanceDayUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AttendanceDayUpdateOne) SetUpdatedAt(v time.Time) *AttendanceDayUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *AttendanceDayUpdateOne) SetUser(v *User) *AttendanceDayUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *AttendanceDayUpdateOne) SetBranch(v *Branch) *AttendanceDayUpdateOne {
	return _u.SetBranchID(v.ID)
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *AttendanceDayUpdateOne) SetAccessPoint(v *AccessPoint) *AttendanceDayUpdateOne {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the AttendanceDayMutation object of the builder.
func (_u *AttendanceDayUpdateOne) Mutation() *AttendanceDayMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *AttendanceDayUpdateOne) ClearUser() *AttendanceDayUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *AttendanceDayUpdateOne) ClearBranch() *AttendanceDayUpdateOne {
	_u.mutation.ClearBranch()
	return _u
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *AttendanceDayUpdateOne) ClearAccessPoint() *AttendanceDayUpdateOne {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Where appends a list predicates to the AttendanceDayUpdate builder.
func (_u *AttendanceDayUpdateOne) Where(ps ...predicate.AttendanceDay) *AttendanceDayUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AttendanceDayUpdateOne) Select(field string, fields ...string) *AttendanceDayUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AttendanceDay entity.
func (_u *AttendanceDayUpdateOne) Save(ctx context.Context) (*AttendanceDay, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AttendanceDayUpdateOne) SaveX(ctx context.Context) *AttendanceDay {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AttendanceDayUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AttendanceDayUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AttendanceDayUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := attendanceday.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AttendanceDayUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttendanceDay.user"`)
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AttendanceDay.branch"`)
	}
	return nil
}

func (_u *AttendanceDayUpdateOne) sqlSave(ctx context.Context) (_node *AttendanceDay, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(attendanceday.Table, attendanceday.Columns, sqlgraph.NewFieldSpec(attendanceday.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AttendanceDay.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, attendanceday.FieldID)
		for _, f := range fields {
			if !attendanceday.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != attendanceday.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WorkDate(); ok {
		_spec.SetField(attendanceday.FieldWorkDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.WorkInAt(); ok {
		_spec.SetField(attendanceday.FieldWorkInAt, field.TypeTime, value)
	}
	if _u.mutation.WorkInAtCleared() {
		_spec.ClearField(attendanceday.FieldWorkInAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreakOutAt(); ok {
		_spec.SetField(attendanceday.FieldBreakOutAt, field.TypeTime, value)
	}
	if _u.mutation.BreakOutAtCleared() {
		_spec.ClearField(attendanceday.FieldBreakOutAt, field.TypeTime)
	}
	if value, ok := _u.mutation.BreakInAt(); ok {
		_spec.SetField(attendanceday.FieldBreakInAt, field.TypeTime, value)
	}
	if _u.mutation.BreakInAtCleared() {
		_spec.ClearField(attendanceday.FieldBreakInAt, field.TypeTime)
	}
	if value, ok := _u.mutation.WorkOutAt(); ok {
		_spec.SetField(attendanceday.FieldWorkOutAt, field.TypeTime, value)
	}
	if _u.mutation.WorkOutAtCleared() {
		_spec.ClearField(attendanceday.FieldWorkOutAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LateMinutes(); ok {
		_spec.SetField(attendanceday.FieldLateMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLateMinutes(); ok {
		_spec.AddField(attendanceday.FieldLateMinutes, field.TypeInt, value)
	}
	if _u.mutation.LateMinutesCleared() {
		_spec.ClearField(attendanceday.FieldLateMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.OvertimeMinutes(); ok {
		_spec.SetField(attendanceday.FieldOvertimeMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOvertimeMinutes(); ok {
		_spec.AddField(attendanceday.FieldOvertimeMinutes, field.TypeInt, value)
	}
	if _u.mutation.OvertimeMinutesCleared() {
		_spec.ClearField(attendanceday.FieldOvertimeMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.EarlyExitMinutes(); ok {
		_spec.SetField(attendanceday.FieldEarlyExitMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedEarlyExitMinutes(); ok {
		_spec.AddField(attendanceday.FieldEarlyExitMinutes, field.TypeInt, value)
	}
	if _u.mutation.EarlyExitMinutesCleared() {
		_spec.ClearField(attendanceday.FieldEarlyExitMinutes, field.TypeInt)
	}
	if value, ok := _u.mutation.Edited(); ok {
		_spec.SetField(attendanceday.FieldEdited, field.TypeBool, value)
	}
	if value, ok := _u.mutation.LastEditReason(); ok {
		_spec.SetField(attendanceday.FieldLastEditReason, field.TypeString, value)
	}
	if _u.mutation.LastEditReasonCleared() {
		_spec.ClearField(attendanceday.FieldLastEditReason, field.TypeString)
	}
	if value, ok := _u.mutation.EditedAt(); ok {
		_spec.SetField(attendanceday.FieldEditedAt, field.TypeTime, value)
	}
	if _u.mutation.EditedAtCleared() {
		_spec.ClearField(attendanceday.FieldEditedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(attendanceday.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(attendanceday.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.UserTable,
			Columns: []string{attendanceday.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.UserTable,
			Columns: []string{attendanceday.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.BranchTable,
			Columns: []string{attendanceday.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.BranchTable,
			Columns: []string{attendanceday.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.AccessPointTable,
			Columns: []string{attendanceday.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   attendanceday.AccessPointTable,
			Columns: []string{attendanceday.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AttendanceDay{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{attendanceday.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
