// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/branch"
	"back/internal/ent/branchaddress"
	"back/internal/ent/commune"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// BranchAddress is the model entity for the BranchAddress schema.
type BranchAddress struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// BranchID holds the value of the "branch_id" field.
	BranchID int `json:"branch_id,omitempty"`
	// CommuneID holds the value of the "commune_id" field.
	CommuneID int `json:"commune_id,omitempty"`
	// Street holds the value of the "street" field.
	Street string `json:"street,omitempty"`
	// Number holds the value of the "number" field.
	Number string `json:"number,omitempty"`
	// Apartment holds the value of the "apartment" field.
	Apartment *string `json:"apartment,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra *string `json:"extra,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BranchAddressQuery when eager-loading is set.
	Edges        BranchAddressEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BranchAddressEdges holds the relations/edges for other nodes in the graph.
type BranchAddressEdges struct {
	// Branch holds the value of the branch edge.
	Branch *Branch `json:"branch,omitempty"`
	// Commune holds the value of the commune edge.
	Commune *Commune `json:"commune,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// BranchOrErr returns the Branch value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BranchAddressEdges) BranchOrErr() (*Branch, error) {
	if e.Branch != nil {
		return e.Branch, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: branch.Label}
	}
	return nil, &NotLoadedError{edge: "branch"}
}

// CommuneOrErr returns the Commune value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BranchAddressEdges) CommuneOrErr() (*Commune, error) {
	if e.Commune != nil {
		return e.Commune, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: commune.Label}
	}
	return nil, &NotLoadedError{edge: "commune"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BranchAddress) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case branchaddress.FieldID, branchaddress.FieldBranchID, branchaddress.FieldCommuneID:
			values[i] = new(sql.NullInt64)
		case branchaddress.FieldStreet, branchaddress.FieldNumber, branchaddress.FieldApartment, branchaddress.FieldExtra:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BranchAddress fields.
func (_m *BranchAddress) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case branchaddress.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case branchaddress.FieldBranchID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field branch_id", values[i])
			} else if value.Valid {
				_m.BranchID = int(value.Int64)
			}
		case branchaddress.FieldCommuneID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field commune_id", values[i])
			} else if value.Valid {
				_m.CommuneID = int(value.Int64)
			}
		case branchaddress.FieldStreet:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field street", values[i])
			} else if value.Valid {
				_m.Street = value.String
			}
		case branchaddress.FieldNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field number", values[i])
			} else if value.Valid {
				_m.Number = value.String
			}
		case branchaddress.FieldApartment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field apartment", values[i])
			} else if value.Valid {
				_m.Apartment = new(string)
				*_m.Apartment = value.String
			}
		case branchaddress.FieldExtra:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value.Valid {
				_m.Extra = new(string)
				*_m.Extra = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BranchAddress.
// This includes values selected through modifiers, order, etc.
func (_m *BranchAddress) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryBranch queries the "branch" edge of the BranchAddress entity.
func (_m *BranchAddress) QueryBranch() *BranchQuery {
	return NewBranchAddressClient(_m.config).QueryBranch(_m)
}

// QueryCommune queries the "commune" edge of the BranchAddress entity.
func (_m *BranchAddress) QueryCommune() *CommuneQuery {
	return NewBranchAddressClient(_m.config).QueryCommune(_m)
}

// Update returns a builder for updating this BranchAddress.
// Note that you need to call BranchAddress.Unwrap() before calling this method if this BranchAddress
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BranchAddress) Update() *BranchAddressUpdateOne {
	return NewBranchAddressClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BranchAddress entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BranchAddress) Unwrap() *BranchAddress {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BranchAddress is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BranchAddress) String() string {
	var builder strings.Builder
	builder.WriteString("BranchAddress(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("branch_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.BranchID))
	builder.WriteString(", ")
	builder.WriteString("commune_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommuneID))
	builder.WriteString(", ")
	builder.WriteString("street=")
	builder.WriteString(_m.Street)
	builder.WriteString(", ")
	builder.WriteString("number=")
	builder.WriteString(_m.Number)
	builder.WriteString(", ")
	if v := _m.Apartment; v != nil {
		builder.WriteString("apartment=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Extra; v != nil {
		builder.WriteString("extra=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// BranchAddresses is a parsable slice of BranchAddress.
type BranchAddresses []*BranchAddress
