// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/city"
	"back/internal/ent/commune"
	"back/internal/ent/predicate"
	"back/internal/ent/region"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CityUpdate is the builder for updating City entities.
type CityUpdate struct {
	config
	hooks    []Hook
	mutation *CityMutation
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdate) Where(ps ...predicate.City) *CityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CityUpdate) SetName(v string) *CityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CityUpdate) SetNillableName(v *string) *CityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdate) SetUpdatedAt(v time.Time) *CityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRegionID sets the "region" edge to the Region entity by ID.
func (_u *CityUpdate) SetRegionID(id int) *CityUpdate {
	_u.mutation.SetRegionID(id)
	return _u
}

// SetRegion sets the "region" edge to the Region entity.
func (_u *CityUpdate) SetRegion(v *Region) *CityUpdate {
	return _u.SetRegionID(v.ID)
}

// AddCommuneIDs adds the "communes" edge to the Commune entity by IDs.
func (_u *CityUpdate) AddCommuneIDs(ids ...int) *CityUpdate {
	_u.mutation.AddCommuneIDs(ids...)
	return _u
}

// AddCommunes adds the "communes" edges to the Commune entity.
func (_u *CityUpdate) AddCommunes(v ...*Commune) *CityUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommuneIDs(ids...)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdate) Mutation() *CityMutation {
	return _u.mutation
}

// ClearRegion clears the "region" edge to the Region entity.
func (_u *CityUpdate) ClearRegion() *CityUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// ClearCommunes clears all "communes" edges to the Commune entity.
func (_u *CityUpdate) ClearCommunes() *CityUpdate {
	_u.mutation.ClearCommunes()
	return _u
}

// RemoveCommuneIDs removes the "communes" edge to Commune entities by IDs.
func (_u *CityUpdate) RemoveCommuneIDs(ids ...int) *CityUpdate {
	_u.mutation.RemoveCommuneIDs(ids...)
	return _u
}

// RemoveCommunes removes "communes" edges to Commune entities.
func (_u *CityUpdate) RemoveCommunes(v ...*Commune) *CityUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommuneIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := city.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "City.name": %w`, err)}
		}
	}
	if _u.mutation.RegionCleared() && len(_u.mutation.RegionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "City.region"`)
	}
	return nil
}

func (_u *CityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RegionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.RegionTable,
			Columns: []string{city.RegionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RegionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.RegionTable,
			Columns: []string{city.RegionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommunesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommunesIDs(); len(nodes) > 0 && !_u.mutation.CommunesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommunesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CityUpdateOne is the builder for updating a single City entity.
type CityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CityMutation
}

// SetName sets the "name" field.
func (_u *CityUpdateOne) SetName(v string) *CityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CityUpdateOne) SetNillableName(v *string) *CityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CityUpdateOne) SetUpdatedAt(v time.Time) *CityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRegionID sets the "region" edge to the Region entity by ID.
func (_u *CityUpdateOne) SetRegionID(id int) *CityUpdateOne {
	_u.mutation.SetRegionID(id)
	return _u
}

// SetRegion sets the "region" edge to the Region entity.
func (_u *CityUpdateOne) SetRegion(v *Region) *CityUpdateOne {
	return _u.SetRegionID(v.ID)
}

// AddCommuneIDs adds the "communes" edge to the Commune entity by IDs.
func (_u *CityUpdateOne) AddCommuneIDs(ids ...int) *CityUpdateOne {
	_u.mutation.AddCommuneIDs(ids...)
	return _u
}

// AddCommunes adds the "communes" edges to the Commune entity.
func (_u *CityUpdateOne) AddCommunes(v ...*Commune) *CityUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddCommuneIDs(ids...)
}

// Mutation returns the CityMutation object of the builder.
func (_u *CityUpdateOne) Mutation() *CityMutation {
	return _u.mutation
}

// ClearRegion clears the "region" edge to the Region entity.
func (_u *CityUpdateOne) ClearRegion() *CityUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// ClearCommunes clears all "communes" edges to the Commune entity.
func (_u *CityUpdateOne) ClearCommunes() *CityUpdateOne {
	_u.mutation.ClearCommunes()
	return _u
}

// RemoveCommuneIDs removes the "communes" edge to Commune entities by IDs.
func (_u *CityUpdateOne) RemoveCommuneIDs(ids ...int) *CityUpdateOne {
	_u.mutation.RemoveCommuneIDs(ids...)
	return _u
}

// RemoveCommunes removes "communes" edges to Commune entities.
func (_u *CityUpdateOne) RemoveCommunes(v ...*Commune) *CityUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveCommuneIDs(ids...)
}

// Where appends a list predicates to the CityUpdate builder.
func (_u *CityUpdateOne) Where(ps ...predicate.City) *CityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CityUpdateOne) Select(field string, fields ...string) *CityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated City entity.
func (_u *CityUpdateOne) Save(ctx context.Context) (*City, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CityUpdateOne) SaveX(ctx context.Context) *City {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := city.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CityUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := city.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "City.name": %w`, err)}
		}
	}
	if _u.mutation.RegionCleared() && len(_u.mutation.RegionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "City.region"`)
	}
	return nil
}

func (_u *CityUpdateOne) sqlSave(ctx context.Context) (_node *City, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(city.Table, city.Columns, sqlgraph.NewFieldSpec(city.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "City.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, city.FieldID)
		for _, f := range fields {
			if !city.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != city.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(city.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(city.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RegionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.RegionTable,
			Columns: []string{city.RegionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RegionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   city.RegionTable,
			Columns: []string{city.RegionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(region.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CommunesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedCommunesIDs(); len(nodes) > 0 && !_u.mutation.CommunesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CommunesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   city.CommunesTable,
			Columns: []string{city.CommunesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(commune.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &City{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{city.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
