// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/accesspoint"
	"back/internal/ent/device"
	"back/internal/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceUpdate is the builder for updating Device entities.
type DeviceUpdate struct {
	config
	hooks    []Hook
	mutation *DeviceMutation
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdate) Where(ps ...predicate.Device) *DeviceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *DeviceUpdate) SetAccessPointID(v int) *DeviceUpdate {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableAccessPointID(v *int) *DeviceUpdate {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdate) SetName(v string) *DeviceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableName(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSerial sets the "serial" field.
func (_u *DeviceUpdate) SetSerial(v string) *DeviceUpdate {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableSerial(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *DeviceUpdate) SetDirection(v string) *DeviceUpdate {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableDirection(v *string) *DeviceUpdate {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DeviceUpdate) SetIsActive(v bool) *DeviceUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DeviceUpdate) SetNillableIsActive(v *bool) *DeviceUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdate) SetUpdatedAt(v time.Time) *DeviceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *DeviceUpdate) SetAccessPoint(v *AccessPoint) *DeviceUpdate {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdate) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *DeviceUpdate) ClearAccessPoint() *DeviceUpdate {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeviceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeviceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := device.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Device.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Serial(); ok {
		if err := device.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "Device.serial": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := device.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Device.direction": %w`, err)}
		}
	}
	if _u.mutation.AccessPointCleared() && len(_u.mutation.AccessPointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.access_point"`)
	}
	return nil
}

func (_u *DeviceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(device.FieldSerial, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(device.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(device.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.AccessPointTable,
			Columns: []string{device.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.AccessPointTable,
			Columns: []string{device.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeviceUpdateOne is the builder for updating a single Device entity.
type DeviceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeviceMutation
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *DeviceUpdateOne) SetAccessPointID(v int) *DeviceUpdateOne {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableAccessPointID(v *int) *DeviceUpdateOne {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *DeviceUpdateOne) SetName(v string) *DeviceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableName(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSerial sets the "serial" field.
func (_u *DeviceUpdateOne) SetSerial(v string) *DeviceUpdateOne {
	_u.mutation.SetSerial(v)
	return _u
}

// SetNillableSerial sets the "serial" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableSerial(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetSerial(*v)
	}
	return _u
}

// SetDirection sets the "direction" field.
func (_u *DeviceUpdateOne) SetDirection(v string) *DeviceUpdateOne {
	_u.mutation.SetDirection(v)
	return _u
}

// SetNillableDirection sets the "direction" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableDirection(v *string) *DeviceUpdateOne {
	if v != nil {
		_u.SetDirection(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *DeviceUpdateOne) SetIsActive(v bool) *DeviceUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *DeviceUpdateOne) SetNillableIsActive(v *bool) *DeviceUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeviceUpdateOne) SetUpdatedAt(v time.Time) *DeviceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *DeviceUpdateOne) SetAccessPoint(v *AccessPoint) *DeviceUpdateOne {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the DeviceMutation object of the builder.
func (_u *DeviceUpdateOne) Mutation() *DeviceMutation {
	return _u.mutation
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *DeviceUpdateOne) ClearAccessPoint() *DeviceUpdateOne {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Where appends a list predicates to the DeviceUpdate builder.
func (_u *DeviceUpdateOne) Where(ps ...predicate.Device) *DeviceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeviceUpdateOne) Select(field string, fields ...string) *DeviceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Device entity.
func (_u *DeviceUpdateOne) Save(ctx context.Context) (*Device, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeviceUpdateOne) SaveX(ctx context.Context) *Device {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeviceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeviceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeviceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := device.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeviceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := device.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Device.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Serial(); ok {
		if err := device.SerialValidator(v); err != nil {
			return &ValidationError{Name: "serial", err: fmt.Errorf(`ent: validator failed for field "Device.serial": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Direction(); ok {
		if err := device.DirectionValidator(v); err != nil {
			return &ValidationError{Name: "direction", err: fmt.Errorf(`ent: validator failed for field "Device.direction": %w`, err)}
		}
	}
	if _u.mutation.AccessPointCleared() && len(_u.mutation.AccessPointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Device.access_point"`)
	}
	return nil
}

func (_u *DeviceUpdateOne) sqlSave(ctx context.Context) (_node *Device, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(device.Table, device.Columns, sqlgraph.NewFieldSpec(device.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Device.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, device.FieldID)
		for _, f := range fields {
			if !device.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != device.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(device.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Serial(); ok {
		_spec.SetField(device.FieldSerial, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direction(); ok {
		_spec.SetField(device.FieldDirection, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(device.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(device.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.AccessPointTable,
			Columns: []string{device.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   device.AccessPointTable,
			Columns: []string{device.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Device{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{device.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
