// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/shift"
	"back/internal/ent/shiftinstance"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShiftInstanceCreate is the builder for creating a ShiftInstance entity.
type ShiftInstanceCreate struct {
	config
	mutation *ShiftInstanceMutation
	hooks    []Hook
}

// SetShiftID sets the "shift_id" field.
func (_c *ShiftInstanceCreate) SetShiftID(v int) *ShiftInstanceCreate {
	_c.mutation.SetShiftID(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *ShiftInstanceCreate) SetDate(v time.Time) *ShiftInstanceCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetState sets the "state" field.
func (_c *ShiftInstanceCreate) SetState(v string) *ShiftInstanceCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ShiftInstanceCreate) SetNillableState(v *string) *ShiftInstanceCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetMode sets the "mode" field.
func (_c *ShiftInstanceCreate) SetMode(v string) *ShiftInstanceCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *ShiftInstanceCreate) SetNillableMode(v *string) *ShiftInstanceCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShiftInstanceCreate) SetCreatedAt(v time.Time) *ShiftInstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShiftInstanceCreate) SetNillableCreatedAt(v *time.Time) *ShiftInstanceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetShift sets the "shift" edge to the Shift entity.
func (_c *ShiftInstanceCreate) SetShift(v *Shift) *ShiftInstanceCreate {
	return _c.SetShiftID(v.ID)
}

// Mutation returns the ShiftInstanceMutation object of the builder.
func (_c *ShiftInstanceCreate) Mutation() *ShiftInstanceMutation {
	return _c.mutation
}

// Save creates the ShiftInstance in the database.
func (_c *ShiftInstanceCreate) Save(ctx context.Context) (*ShiftInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShiftInstanceCreate) SaveX(ctx context.Context) *ShiftInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShiftInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShiftInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShiftInstanceCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := shiftinstance.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := shiftinstance.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shiftinstance.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShiftInstanceCreate) check() error {
	if _, ok := _c.mutation.ShiftID(); !ok {
		return &ValidationError{Name: "shift_id", err: errors.New(`ent: missing required field "ShiftInstance.shift_id"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "ShiftInstance.date"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ShiftInstance.state"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "ShiftInstance.mode"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ShiftInstance.created_at"`)}
	}
	if len(_c.mutation.ShiftIDs()) == 0 {
		return &ValidationError{Name: "shift", err: errors.New(`ent: missing required edge "ShiftInstance.shift"`)}
	}
	return nil
}

func (_c *ShiftInstanceCreate) sqlSave(ctx context.Context) (*ShiftInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShiftInstanceCreate) createSpec() (*ShiftInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &ShiftInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shiftinstance.Table, sqlgraph.NewFieldSpec(shiftinstance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(shiftinstance.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(shiftinstance.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(shiftinstance.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shiftinstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ShiftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shiftinstance.ShiftTable,
			Columns: []string{shiftinstance.ShiftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShiftID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShiftInstanceCreateBulk is the builder for creating many ShiftInstance entities in bulk.
type ShiftInstanceCreateBulk struct {
	config
	err      error
	builders []*ShiftInstanceCreate
}

// Save creates the ShiftInstance entities in the database.
func (_c *ShiftInstanceCreateBulk) Save(ctx context.Context) ([]*ShiftInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ShiftInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShiftInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShiftInstanceCreateBulk) SaveX(ctx context.Context) []*ShiftInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShiftInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShiftInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
