// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/predicate"
	"back/internal/ent/shiftday"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShiftDayDelete is the builder for deleting a ShiftDay entity.
type ShiftDayDelete struct {
	config
	hooks    []Hook
	mutation *ShiftDayMutation
}

// Where appends a list predicates to the ShiftDayDelete builder.
func (_d *ShiftDayDelete) Where(ps ...predicate.ShiftDay) *ShiftDayDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShiftDayDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShiftDayDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShiftDayDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shiftday.Table, sqlgraph.NewFieldSpec(shiftday.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShiftDayDeleteOne is the builder for deleting a single ShiftDay entity.
type ShiftDayDeleteOne struct {
	_d *ShiftDayDelete
}

// Where appends a list predicates to the ShiftDayDelete builder.
func (_d *ShiftDayDeleteOne) Where(ps ...predicate.ShiftDay) *ShiftDayDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShiftDayDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shiftday.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShiftDayDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
