// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/accesspoint"
	"back/internal/ent/predicate"
	"back/internal/ent/user"
	"back/internal/ent/useraccesspoint"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAccessPointUpdate is the builder for updating UserAccessPoint entities.
type UserAccessPointUpdate struct {
	config
	hooks    []Hook
	mutation *UserAccessPointMutation
}

// Where appends a list predicates to the UserAccessPointUpdate builder.
func (_u *UserAccessPointUpdate) Where(ps ...predicate.UserAccessPoint) *UserAccessPointUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAccessPointUpdate) SetUserID(v int) *UserAccessPointUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAccessPointUpdate) SetNillableUserID(v *int) *UserAccessPointUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *UserAccessPointUpdate) SetAccessPointID(v int) *UserAccessPointUpdate {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *UserAccessPointUpdate) SetNillableAccessPointID(v *int) *UserAccessPointUpdate {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserAccessPointUpdate) SetIsActive(v bool) *UserAccessPointUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserAccessPointUpdate) SetNillableIsActive(v *bool) *UserAccessPointUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserAccessPointUpdate) SetAssignedAt(v time.Time) *UserAccessPointUpdate {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserAccessPointUpdate) SetNillableAssignedAt(v *time.Time) *UserAccessPointUpdate {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UserAccessPointUpdate) SetRevokedAt(v time.Time) *UserAccessPointUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UserAccessPointUpdate) SetNillableRevokedAt(v *time.Time) *UserAccessPointUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UserAccessPointUpdate) ClearRevokedAt() *UserAccessPointUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAccessPointUpdate) SetUser(v *User) *UserAccessPointUpdate {
	return _u.SetUserID(v.ID)
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *UserAccessPointUpdate) SetAccessPoint(v *AccessPoint) *UserAccessPointUpdate {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the UserAccessPointMutation object of the builder.
func (_u *UserAccessPointUpdate) Mutation() *UserAccessPointMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAccessPointUpdate) ClearUser() *UserAccessPointUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *UserAccessPointUpdate) ClearAccessPoint() *UserAccessPointUpdate {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAccessPointUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccessPointUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAccessPointUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccessPointUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccessPointUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccessPoint.user"`)
	}
	if _u.mutation.AccessPointCleared() && len(_u.mutation.AccessPointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccessPoint.access_point"`)
	}
	return nil
}

func (_u *UserAccessPointUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccesspoint.Table, useraccesspoint.Columns, sqlgraph.NewFieldSpec(useraccesspoint.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(useraccesspoint.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(useraccesspoint.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(useraccesspoint.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(useraccesspoint.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.UserTable,
			Columns: []string{useraccesspoint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.UserTable,
			Columns: []string{useraccesspoint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.AccessPointTable,
			Columns: []string{useraccesspoint.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.AccessPointTable,
			Columns: []string{useraccesspoint.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccesspoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAccessPointUpdateOne is the builder for updating a single UserAccessPoint entity.
type UserAccessPointUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAccessPointMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserAccessPointUpdateOne) SetUserID(v int) *UserAccessPointUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAccessPointUpdateOne) SetNillableUserID(v *int) *UserAccessPointUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccessPointID sets the "access_point_id" field.
func (_u *UserAccessPointUpdateOne) SetAccessPointID(v int) *UserAccessPointUpdateOne {
	_u.mutation.SetAccessPointID(v)
	return _u
}

// SetNillableAccessPointID sets the "access_point_id" field if the given value is not nil.
func (_u *UserAccessPointUpdateOne) SetNillableAccessPointID(v *int) *UserAccessPointUpdateOne {
	if v != nil {
		_u.SetAccessPointID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserAccessPointUpdateOne) SetIsActive(v bool) *UserAccessPointUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserAccessPointUpdateOne) SetNillableIsActive(v *bool) *UserAccessPointUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetAssignedAt sets the "assigned_at" field.
func (_u *UserAccessPointUpdateOne) SetAssignedAt(v time.Time) *UserAccessPointUpdateOne {
	_u.mutation.SetAssignedAt(v)
	return _u
}

// SetNillableAssignedAt sets the "assigned_at" field if the given value is not nil.
func (_u *UserAccessPointUpdateOne) SetNillableAssignedAt(v *time.Time) *UserAccessPointUpdateOne {
	if v != nil {
		_u.SetAssignedAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *UserAccessPointUpdateOne) SetRevokedAt(v time.Time) *UserAccessPointUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *UserAccessPointUpdateOne) SetNillableRevokedAt(v *time.Time) *UserAccessPointUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *UserAccessPointUpdateOne) ClearRevokedAt() *UserAccessPointUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAccessPointUpdateOne) SetUser(v *User) *UserAccessPointUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAccessPoint sets the "access_point" edge to the AccessPoint entity.
func (_u *UserAccessPointUpdateOne) SetAccessPoint(v *AccessPoint) *UserAccessPointUpdateOne {
	return _u.SetAccessPointID(v.ID)
}

// Mutation returns the UserAccessPointMutation object of the builder.
func (_u *UserAccessPointUpdateOne) Mutation() *UserAccessPointMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAccessPointUpdateOne) ClearUser() *UserAccessPointUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccessPoint clears the "access_point" edge to the AccessPoint entity.
func (_u *UserAccessPointUpdateOne) ClearAccessPoint() *UserAccessPointUpdateOne {
	_u.mutation.ClearAccessPoint()
	return _u
}

// Where appends a list predicates to the UserAccessPointUpdate builder.
func (_u *UserAccessPointUpdateOne) Where(ps ...predicate.UserAccessPoint) *UserAccessPointUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAccessPointUpdateOne) Select(field string, fields ...string) *UserAccessPointUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAccessPoint entity.
func (_u *UserAccessPointUpdateOne) Save(ctx context.Context) (*UserAccessPoint, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAccessPointUpdateOne) SaveX(ctx context.Context) *UserAccessPoint {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAccessPointUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAccessPointUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAccessPointUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccessPoint.user"`)
	}
	if _u.mutation.AccessPointCleared() && len(_u.mutation.AccessPointIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAccessPoint.access_point"`)
	}
	return nil
}

func (_u *UserAccessPointUpdateOne) sqlSave(ctx context.Context) (_node *UserAccessPoint, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useraccesspoint.Table, useraccesspoint.Columns, sqlgraph.NewFieldSpec(useraccesspoint.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserAccessPoint.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useraccesspoint.FieldID)
		for _, f := range fields {
			if !useraccesspoint.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useraccesspoint.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(useraccesspoint.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AssignedAt(); ok {
		_spec.SetField(useraccesspoint.FieldAssignedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(useraccesspoint.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(useraccesspoint.FieldRevokedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.UserTable,
			Columns: []string{useraccesspoint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.UserTable,
			Columns: []string{useraccesspoint.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccessPointCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.AccessPointTable,
			Columns: []string{useraccesspoint.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccessPointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useraccesspoint.AccessPointTable,
			Columns: []string{useraccesspoint.AccessPointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accesspoint.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAccessPoint{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useraccesspoint.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
