// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/predicate"
	"back/internal/ent/userdayoverride"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDayOverrideDelete is the builder for deleting a UserDayOverride entity.
type UserDayOverrideDelete struct {
	config
	hooks    []Hook
	mutation *UserDayOverrideMutation
}

// Where appends a list predicates to the UserDayOverrideDelete builder.
func (_d *UserDayOverrideDelete) Where(ps ...predicate.UserDayOverride) *UserDayOverrideDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserDayOverrideDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDayOverrideDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserDayOverrideDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(userdayoverride.Table, sqlgraph.NewFieldSpec(userdayoverride.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserDayOverrideDeleteOne is the builder for deleting a single UserDayOverride entity.
type UserDayOverrideDeleteOne struct {
	_d *UserDayOverrideDelete
}

// Where appends a list predicates to the UserDayOverrideDelete builder.
func (_d *UserDayOverrideDeleteOne) Where(ps ...predicate.UserDayOverride) *UserDayOverrideDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserDayOverrideDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{userdayoverride.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserDayOverrideDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
