// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/predicate"
	"back/internal/ent/useraccesspoint"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserAccessPointDelete is the builder for deleting a UserAccessPoint entity.
type UserAccessPointDelete struct {
	config
	hooks    []Hook
	mutation *UserAccessPointMutation
}

// Where appends a list predicates to the UserAccessPointDelete builder.
func (_d *UserAccessPointDelete) Where(ps ...predicate.UserAccessPoint) *UserAccessPointDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserAccessPointDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserAccessPointDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserAccessPointDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(useraccesspoint.Table, sqlgraph.NewFieldSpec(useraccesspoint.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserAccessPointDeleteOne is the builder for deleting a single UserAccessPoint entity.
type UserAccessPointDeleteOne struct {
	_d *UserAccessPointDelete
}

// Where appends a list predicates to the UserAccessPointDelete builder.
func (_d *UserAccessPointDeleteOne) Where(ps ...predicate.UserAccessPoint) *UserAccessPointDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserAccessPointDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{useraccesspoint.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserAccessPointDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
