// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/branch"
	"back/internal/ent/predicate"
	"back/internal/ent/user"
	"back/internal/ent/userbranch"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserBranchUpdate is the builder for updating UserBranch entities.
type UserBranchUpdate struct {
	config
	hooks    []Hook
	mutation *UserBranchMutation
}

// Where appends a list predicates to the UserBranchUpdate builder.
func (_u *UserBranchUpdate) Where(ps ...predicate.UserBranch) *UserBranchUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserBranchUpdate) SetUserID(v int) *UserBranchUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBranchUpdate) SetNillableUserID(v *int) *UserBranchUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *UserBranchUpdate) SetBranchID(v int) *UserBranchUpdate {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *UserBranchUpdate) SetNillableBranchID(v *int) *UserBranchUpdate {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserBranchUpdate) SetIsActive(v bool) *UserBranchUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserBranchUpdate) SetNillableIsActive(v *bool) *UserBranchUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRoleInBranch sets the "role_in_branch" field.
func (_u *UserBranchUpdate) SetRoleInBranch(v string) *UserBranchUpdate {
	_u.mutation.SetRoleInBranch(v)
	return _u
}

// SetNillableRoleInBranch sets the "role_in_branch" field if the given value is not nil.
func (_u *UserBranchUpdate) SetNillableRoleInBranch(v *string) *UserBranchUpdate {
	if v != nil {
		_u.SetRoleInBranch(*v)
	}
	return _u
}

// ClearRoleInBranch clears the value of the "role_in_branch" field.
func (_u *UserBranchUpdate) ClearRoleInBranch() *UserBranchUpdate {
	_u.mutation.ClearRoleInBranch()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBranchUpdate) SetUser(v *User) *UserBranchUpdate {
	return _u.SetUserID(v.ID)
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *UserBranchUpdate) SetBranch(v *Branch) *UserBranchUpdate {
	return _u.SetBranchID(v.ID)
}

// Mutation returns the UserBranchMutation object of the builder.
func (_u *UserBranchUpdate) Mutation() *UserBranchMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBranchUpdate) ClearUser() *UserBranchUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *UserBranchUpdate) ClearBranch() *UserBranchUpdate {
	_u.mutation.ClearBranch()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserBranchUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBranchUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserBranchUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBranchUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBranchUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBranch.user"`)
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBranch.branch"`)
	}
	return nil
}

func (_u *UserBranchUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbranch.Table, userbranch.Columns, sqlgraph.NewFieldSpec(userbranch.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(userbranch.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RoleInBranch(); ok {
		_spec.SetField(userbranch.FieldRoleInBranch, field.TypeString, value)
	}
	if _u.mutation.RoleInBranchCleared() {
		_spec.ClearField(userbranch.FieldRoleInBranch, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.UserTable,
			Columns: []string{userbranch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.UserTable,
			Columns: []string{userbranch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.BranchTable,
			Columns: []string{userbranch.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.BranchTable,
			Columns: []string{userbranch.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbranch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserBranchUpdateOne is the builder for updating a single UserBranch entity.
type UserBranchUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserBranchMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserBranchUpdateOne) SetUserID(v int) *UserBranchUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserBranchUpdateOne) SetNillableUserID(v *int) *UserBranchUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetBranchID sets the "branch_id" field.
func (_u *UserBranchUpdateOne) SetBranchID(v int) *UserBranchUpdateOne {
	_u.mutation.SetBranchID(v)
	return _u
}

// SetNillableBranchID sets the "branch_id" field if the given value is not nil.
func (_u *UserBranchUpdateOne) SetNillableBranchID(v *int) *UserBranchUpdateOne {
	if v != nil {
		_u.SetBranchID(*v)
	}
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *UserBranchUpdateOne) SetIsActive(v bool) *UserBranchUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *UserBranchUpdateOne) SetNillableIsActive(v *bool) *UserBranchUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetRoleInBranch sets the "role_in_branch" field.
func (_u *UserBranchUpdateOne) SetRoleInBranch(v string) *UserBranchUpdateOne {
	_u.mutation.SetRoleInBranch(v)
	return _u
}

// SetNillableRoleInBranch sets the "role_in_branch" field if the given value is not nil.
func (_u *UserBranchUpdateOne) SetNillableRoleInBranch(v *string) *UserBranchUpdateOne {
	if v != nil {
		_u.SetRoleInBranch(*v)
	}
	return _u
}

// ClearRoleInBranch clears the value of the "role_in_branch" field.
func (_u *UserBranchUpdateOne) ClearRoleInBranch() *UserBranchUpdateOne {
	_u.mutation.ClearRoleInBranch()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserBranchUpdateOne) SetUser(v *User) *UserBranchUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetBranch sets the "branch" edge to the Branch entity.
func (_u *UserBranchUpdateOne) SetBranch(v *Branch) *UserBranchUpdateOne {
	return _u.SetBranchID(v.ID)
}

// Mutation returns the UserBranchMutation object of the builder.
func (_u *UserBranchUpdateOne) Mutation() *UserBranchMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserBranchUpdateOne) ClearUser() *UserBranchUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearBranch clears the "branch" edge to the Branch entity.
func (_u *UserBranchUpdateOne) ClearBranch() *UserBranchUpdateOne {
	_u.mutation.ClearBranch()
	return _u
}

// Where appends a list predicates to the UserBranchUpdate builder.
func (_u *UserBranchUpdateOne) Where(ps ...predicate.UserBranch) *UserBranchUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserBranchUpdateOne) Select(field string, fields ...string) *UserBranchUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserBranch entity.
func (_u *UserBranchUpdateOne) Save(ctx context.Context) (*UserBranch, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserBranchUpdateOne) SaveX(ctx context.Context) *UserBranch {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserBranchUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserBranchUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserBranchUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBranch.user"`)
	}
	if _u.mutation.BranchCleared() && len(_u.mutation.BranchIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserBranch.branch"`)
	}
	return nil
}

func (_u *UserBranchUpdateOne) sqlSave(ctx context.Context) (_node *UserBranch, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userbranch.Table, userbranch.Columns, sqlgraph.NewFieldSpec(userbranch.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserBranch.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userbranch.FieldID)
		for _, f := range fields {
			if !userbranch.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userbranch.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(userbranch.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RoleInBranch(); ok {
		_spec.SetField(userbranch.FieldRoleInBranch, field.TypeString, value)
	}
	if _u.mutation.RoleInBranchCleared() {
		_spec.ClearField(userbranch.FieldRoleInBranch, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.UserTable,
			Columns: []string{userbranch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.UserTable,
			Columns: []string{userbranch.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BranchCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.BranchTable,
			Columns: []string{userbranch.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BranchIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userbranch.BranchTable,
			Columns: []string{userbranch.BranchColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(branch.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserBranch{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userbranch.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
