// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/predicate"
	"back/internal/ent/usershiftassignment"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserShiftAssignmentDelete is the builder for deleting a UserShiftAssignment entity.
type UserShiftAssignmentDelete struct {
	config
	hooks    []Hook
	mutation *UserShiftAssignmentMutation
}

// Where appends a list predicates to the UserShiftAssignmentDelete builder.
func (_d *UserShiftAssignmentDelete) Where(ps ...predicate.UserShiftAssignment) *UserShiftAssignmentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *UserShiftAssignmentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserShiftAssignmentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *UserShiftAssignmentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(usershiftassignment.Table, sqlgraph.NewFieldSpec(usershiftassignment.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// UserShiftAssignmentDeleteOne is the builder for deleting a single UserShiftAssignment entity.
type UserShiftAssignmentDeleteOne struct {
	_d *UserShiftAssignmentDelete
}

// Where appends a list predicates to the UserShiftAssignmentDelete builder.
func (_d *UserShiftAssignmentDeleteOne) Where(ps ...predicate.UserShiftAssignment) *UserShiftAssignmentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *UserShiftAssignmentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{usershiftassignment.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *UserShiftAssignmentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
