// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/predicate"
	"back/internal/ent/shift"
	"back/internal/ent/user"
	"back/internal/ent/userdayoverride"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserDayOverrideUpdate is the builder for updating UserDayOverride entities.
type UserDayOverrideUpdate struct {
	config
	hooks    []Hook
	mutation *UserDayOverrideMutation
}

// Where appends a list predicates to the UserDayOverrideUpdate builder.
func (_u *UserDayOverrideUpdate) Where(ps ...predicate.UserDayOverride) *UserDayOverrideUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserDayOverrideUpdate) SetUserID(v int) *UserDayOverrideUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableUserID(v *int) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetShiftID sets the "shift_id" field.
func (_u *UserDayOverrideUpdate) SetShiftID(v int) *UserDayOverrideUpdate {
	_u.mutation.SetShiftID(v)
	return _u
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableShiftID(v *int) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetShiftID(*v)
	}
	return _u
}

// ClearShiftID clears the value of the "shift_id" field.
func (_u *UserDayOverrideUpdate) ClearShiftID() *UserDayOverrideUpdate {
	_u.mutation.ClearShiftID()
	return _u
}

// SetDate sets the "date" field.
func (_u *UserDayOverrideUpdate) SetDate(v time.Time) *UserDayOverrideUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableDate(v *time.Time) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetIsDayOff sets the "is_day_off" field.
func (_u *UserDayOverrideUpdate) SetIsDayOff(v bool) *UserDayOverrideUpdate {
	_u.mutation.SetIsDayOff(v)
	return _u
}

// SetNillableIsDayOff sets the "is_day_off" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableIsDayOff(v *bool) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetIsDayOff(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *UserDayOverrideUpdate) SetMode(v string) *UserDayOverrideUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableMode(v *string) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserDayOverrideUpdate) SetNotes(v string) *UserDayOverrideUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserDayOverrideUpdate) SetNillableNotes(v *string) *UserDayOverrideUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserDayOverrideUpdate) ClearNotes() *UserDayOverrideUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserDayOverrideUpdate) SetUser(v *User) *UserDayOverrideUpdate {
	return _u.SetUserID(v.ID)
}

// SetShift sets the "shift" edge to the Shift entity.
func (_u *UserDayOverrideUpdate) SetShift(v *Shift) *UserDayOverrideUpdate {
	return _u.SetShiftID(v.ID)
}

// Mutation returns the UserDayOverrideMutation object of the builder.
func (_u *UserDayOverrideUpdate) Mutation() *UserDayOverrideMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserDayOverrideUpdate) ClearUser() *UserDayOverrideUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearShift clears the "shift" edge to the Shift entity.
func (_u *UserDayOverrideUpdate) ClearShift() *UserDayOverrideUpdate {
	_u.mutation.ClearShift()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserDayOverrideUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDayOverrideUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserDayOverrideUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDayOverrideUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDayOverrideUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDayOverride.user"`)
	}
	return nil
}

func (_u *UserDayOverrideUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdayoverride.Table, userdayoverride.Columns, sqlgraph.NewFieldSpec(userdayoverride.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(userdayoverride.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDayOff(); ok {
		_spec.SetField(userdayoverride.FieldIsDayOff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(userdayoverride.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userdayoverride.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userdayoverride.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.UserTable,
			Columns: []string{userdayoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.UserTable,
			Columns: []string{userdayoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShiftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.ShiftTable,
			Columns: []string{userdayoverride.ShiftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShiftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.ShiftTable,
			Columns: []string{userdayoverride.ShiftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdayoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserDayOverrideUpdateOne is the builder for updating a single UserDayOverride entity.
type UserDayOverrideUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserDayOverrideMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserDayOverrideUpdateOne) SetUserID(v int) *UserDayOverrideUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableUserID(v *int) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetShiftID sets the "shift_id" field.
func (_u *UserDayOverrideUpdateOne) SetShiftID(v int) *UserDayOverrideUpdateOne {
	_u.mutation.SetShiftID(v)
	return _u
}

// SetNillableShiftID sets the "shift_id" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableShiftID(v *int) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetShiftID(*v)
	}
	return _u
}

// ClearShiftID clears the value of the "shift_id" field.
func (_u *UserDayOverrideUpdateOne) ClearShiftID() *UserDayOverrideUpdateOne {
	_u.mutation.ClearShiftID()
	return _u
}

// SetDate sets the "date" field.
func (_u *UserDayOverrideUpdateOne) SetDate(v time.Time) *UserDayOverrideUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableDate(v *time.Time) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetIsDayOff sets the "is_day_off" field.
func (_u *UserDayOverrideUpdateOne) SetIsDayOff(v bool) *UserDayOverrideUpdateOne {
	_u.mutation.SetIsDayOff(v)
	return _u
}

// SetNillableIsDayOff sets the "is_day_off" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableIsDayOff(v *bool) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetIsDayOff(*v)
	}
	return _u
}

// SetMode sets the "mode" field.
func (_u *UserDayOverrideUpdateOne) SetMode(v string) *UserDayOverrideUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableMode(v *string) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *UserDayOverrideUpdateOne) SetNotes(v string) *UserDayOverrideUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *UserDayOverrideUpdateOne) SetNillableNotes(v *string) *UserDayOverrideUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *UserDayOverrideUpdateOne) ClearNotes() *UserDayOverrideUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserDayOverrideUpdateOne) SetUser(v *User) *UserDayOverrideUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetShift sets the "shift" edge to the Shift entity.
func (_u *UserDayOverrideUpdateOne) SetShift(v *Shift) *UserDayOverrideUpdateOne {
	return _u.SetShiftID(v.ID)
}

// Mutation returns the UserDayOverrideMutation object of the builder.
func (_u *UserDayOverrideUpdateOne) Mutation() *UserDayOverrideMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserDayOverrideUpdateOne) ClearUser() *UserDayOverrideUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearShift clears the "shift" edge to the Shift entity.
func (_u *UserDayOverrideUpdateOne) ClearShift() *UserDayOverrideUpdateOne {
	_u.mutation.ClearShift()
	return _u
}

// Where appends a list predicates to the UserDayOverrideUpdate builder.
func (_u *UserDayOverrideUpdateOne) Where(ps ...predicate.UserDayOverride) *UserDayOverrideUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserDayOverrideUpdateOne) Select(field string, fields ...string) *UserDayOverrideUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserDayOverride entity.
func (_u *UserDayOverrideUpdateOne) Save(ctx context.Context) (*UserDayOverride, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserDayOverrideUpdateOne) SaveX(ctx context.Context) *UserDayOverride {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserDayOverrideUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserDayOverrideUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserDayOverrideUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserDayOverride.user"`)
	}
	return nil
}

func (_u *UserDayOverrideUpdateOne) sqlSave(ctx context.Context) (_node *UserDayOverride, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userdayoverride.Table, userdayoverride.Columns, sqlgraph.NewFieldSpec(userdayoverride.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserDayOverride.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userdayoverride.FieldID)
		for _, f := range fields {
			if !userdayoverride.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userdayoverride.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(userdayoverride.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDayOff(); ok {
		_spec.SetField(userdayoverride.FieldIsDayOff, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(userdayoverride.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(userdayoverride.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(userdayoverride.FieldNotes, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.UserTable,
			Columns: []string{userdayoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.UserTable,
			Columns: []string{userdayoverride.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ShiftCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.ShiftTable,
			Columns: []string{userdayoverride.ShiftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShiftIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userdayoverride.ShiftTable,
			Columns: []string{userdayoverride.ShiftColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserDayOverride{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userdayoverride.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
