// Code generated by ent, DO NOT EDIT.

package ent

import (
	"back/internal/ent/shift"
	"back/internal/ent/user"
	"back/internal/ent/userdayoverride"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UserDayOverride is the model entity for the UserDayOverride schema.
type UserDayOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// ShiftID holds the value of the "shift_id" field.
	ShiftID *int `json:"shift_id,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// IsDayOff holds the value of the "is_day_off" field.
	IsDayOff bool `json:"is_day_off,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserDayOverrideQuery when eager-loading is set.
	Edges        UserDayOverrideEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserDayOverrideEdges holds the relations/edges for other nodes in the graph.
type UserDayOverrideEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Shift holds the value of the shift edge.
	Shift *Shift `json:"shift,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserDayOverrideEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// ShiftOrErr returns the Shift value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserDayOverrideEdges) ShiftOrErr() (*Shift, error) {
	if e.Shift != nil {
		return e.Shift, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: shift.Label}
	}
	return nil, &NotLoadedError{edge: "shift"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserDayOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userdayoverride.FieldIsDayOff:
			values[i] = new(sql.NullBool)
		case userdayoverride.FieldID, userdayoverride.FieldUserID, userdayoverride.FieldShiftID:
			values[i] = new(sql.NullInt64)
		case userdayoverride.FieldMode, userdayoverride.FieldNotes:
			values[i] = new(sql.NullString)
		case userdayoverride.FieldDate, userdayoverride.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserDayOverride fields.
func (_m *UserDayOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userdayoverride.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userdayoverride.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case userdayoverride.FieldShiftID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shift_id", values[i])
			} else if value.Valid {
				_m.ShiftID = new(int)
				*_m.ShiftID = int(value.Int64)
			}
		case userdayoverride.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case userdayoverride.FieldIsDayOff:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_day_off", values[i])
			} else if value.Valid {
				_m.IsDayOff = value.Bool
			}
		case userdayoverride.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case userdayoverride.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case userdayoverride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserDayOverride.
// This includes values selected through modifiers, order, etc.
func (_m *UserDayOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserDayOverride entity.
func (_m *UserDayOverride) QueryUser() *UserQuery {
	return NewUserDayOverrideClient(_m.config).QueryUser(_m)
}

// QueryShift queries the "shift" edge of the UserDayOverride entity.
func (_m *UserDayOverride) QueryShift() *ShiftQuery {
	return NewUserDayOverrideClient(_m.config).QueryShift(_m)
}

// Update returns a builder for updating this UserDayOverride.
// Note that you need to call UserDayOverride.Unwrap() before calling this method if this UserDayOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserDayOverride) Update() *UserDayOverrideUpdateOne {
	return NewUserDayOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserDayOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserDayOverride) Unwrap() *UserDayOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserDayOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserDayOverride) String() string {
	var builder strings.Builder
	builder.WriteString("UserDayOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.ShiftID; v != nil {
		builder.WriteString("shift_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_day_off=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDayOff))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserDayOverrides is a parsable slice of UserDayOverride.
type UserDayOverrides []*UserDayOverride
