// Code generated by ent, DO NOT EDIT.

package shift

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the shift type in the database.
	Label = "shift"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldBreakMinutes holds the string denoting the break_minutes field in the database.
	FieldBreakMinutes = "break_minutes"
	// FieldCrossesMidnight holds the string denoting the crosses_midnight field in the database.
	FieldCrossesMidnight = "crosses_midnight"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeDays holds the string denoting the days edge name in mutations.
	EdgeDays = "days"
	// EdgeUserAssignments holds the string denoting the user_assignments edge name in mutations.
	EdgeUserAssignments = "user_assignments"
	// EdgeDayOverrides holds the string denoting the day_overrides edge name in mutations.
	EdgeDayOverrides = "day_overrides"
	// Table holds the table name of the shift in the database.
	Table = "shifts"
	// DaysTable is the table that holds the days relation/edge.
	DaysTable = "shift_days"
	// DaysInverseTable is the table name for the ShiftDay entity.
	// It exists in this package in order to avoid circular dependency with the "shiftday" package.
	DaysInverseTable = "shift_days"
	// DaysColumn is the table column denoting the days relation/edge.
	DaysColumn = "shift_id"
	// UserAssignmentsTable is the table that holds the user_assignments relation/edge.
	UserAssignmentsTable = "user_shift_assignments"
	// UserAssignmentsInverseTable is the table name for the UserShiftAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "usershiftassignment" package.
	UserAssignmentsInverseTable = "user_shift_assignments"
	// UserAssignmentsColumn is the table column denoting the user_assignments relation/edge.
	UserAssignmentsColumn = "shift_id"
	// DayOverridesTable is the table that holds the day_overrides relation/edge.
	DayOverridesTable = "user_day_overrides"
	// DayOverridesInverseTable is the table name for the UserDayOverride entity.
	// It exists in this package in order to avoid circular dependency with the "userdayoverride" package.
	DayOverridesInverseTable = "user_day_overrides"
	// DayOverridesColumn is the table column denoting the day_overrides relation/edge.
	DayOverridesColumn = "shift_id"
)

// Columns holds all SQL columns for shift fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDescription,
	FieldStartTime,
	FieldEndTime,
	FieldBreakMinutes,
	FieldCrossesMidnight,
	FieldIsActive,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StartTimeValidator is a validator for the "start_time" field. It is called by the builders before save.
	StartTimeValidator func(string) error
	// EndTimeValidator is a validator for the "end_time" field. It is called by the builders before save.
	EndTimeValidator func(string) error
	// DefaultBreakMinutes holds the default value on creation for the "break_minutes" field.
	DefaultBreakMinutes int
	// DefaultCrossesMidnight holds the default value on creation for the "crosses_midnight" field.
	DefaultCrossesMidnight bool
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Shift queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByBreakMinutes orders the results by the break_minutes field.
func ByBreakMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBreakMinutes, opts...).ToFunc()
}

// ByCrossesMidnight orders the results by the crosses_midnight field.
func ByCrossesMidnight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCrossesMidnight, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDaysCount orders the results by days count.
func ByDaysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDaysStep(), opts...)
	}
}

// ByDays orders the results by days terms.
func ByDays(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDaysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserAssignmentsCount orders the results by user_assignments count.
func ByUserAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserAssignmentsStep(), opts...)
	}
}

// ByUserAssignments orders the results by user_assignments terms.
func ByUserAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDayOverridesCount orders the results by day_overrides count.
func ByDayOverridesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDayOverridesStep(), opts...)
	}
}

// ByDayOverrides orders the results by day_overrides terms.
func ByDayOverrides(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDayOverridesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newDaysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DaysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DaysTable, DaysColumn),
	)
}
func newUserAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserAssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserAssignmentsTable, UserAssignmentsColumn),
	)
}
func newDayOverridesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DayOverridesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DayOverridesTable, DayOverridesColumn),
	)
}
