// Code generated by ent, DO NOT EDIT.

package accesspoint

import (
	"back/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldLTE(FieldID, id))
}

// BranchID applies equality check predicate on the "branch_id" field. It's identical to BranchIDEQ.
func BranchID(v int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldBranchID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldName, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldIsActive, v))
}

// BranchIDEQ applies the EQ predicate on the "branch_id" field.
func BranchIDEQ(v int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldBranchID, v))
}

// BranchIDNEQ applies the NEQ predicate on the "branch_id" field.
func BranchIDNEQ(v int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNEQ(FieldBranchID, v))
}

// BranchIDIn applies the In predicate on the "branch_id" field.
func BranchIDIn(vs ...int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldIn(FieldBranchID, vs...))
}

// BranchIDNotIn applies the NotIn predicate on the "branch_id" field.
func BranchIDNotIn(vs ...int) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNotIn(FieldBranchID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldContainsFold(FieldName, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.AccessPoint {
	return predicate.AccessPoint(sql.FieldNEQ(FieldIsActive, v))
}

// HasBranch applies the HasEdge predicate on the "branch" edge.
func HasBranch() predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, BranchTable, BranchColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBranchWith applies the HasEdge predicate on the "branch" edge with a given conditions (other predicates).
func HasBranchWith(preds ...predicate.Branch) predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := newBranchStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserAccessPoints applies the HasEdge predicate on the "user_access_points" edge.
func HasUserAccessPoints() predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserAccessPointsTable, UserAccessPointsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserAccessPointsWith applies the HasEdge predicate on the "user_access_points" edge with a given conditions (other predicates).
func HasUserAccessPointsWith(preds ...predicate.UserAccessPoint) predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := newUserAccessPointsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAttendanceDays applies the HasEdge predicate on the "attendance_days" edge.
func HasAttendanceDays() predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AttendanceDaysTable, AttendanceDaysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAttendanceDaysWith applies the HasEdge predicate on the "attendance_days" edge with a given conditions (other predicates).
func HasAttendanceDaysWith(preds ...predicate.AttendanceDay) predicate.AccessPoint {
	return predicate.AccessPoint(func(s *sql.Selector) {
		step := newAttendanceDaysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccessPoint) predicate.AccessPoint {
	return predicate.AccessPoint(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccessPoint) predicate.AccessPoint {
	return predicate.AccessPoint(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccessPoint) predicate.AccessPoint {
	return predicate.AccessPoint(sql.NotPredicates(p))
}
