// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldMiddleName holds the string denoting the middle_name field in the database.
	FieldMiddleName = "middle_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldEmployeeCode holds the string denoting the employee_code field in the database.
	FieldEmployeeCode = "employee_code"
	// FieldAccessCode holds the string denoting the access_code field in the database.
	FieldAccessCode = "access_code"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeRefreshTokens holds the string denoting the refresh_tokens edge name in mutations.
	EdgeRefreshTokens = "refresh_tokens"
	// EdgeAddresses holds the string denoting the addresses edge name in mutations.
	EdgeAddresses = "addresses"
	// EdgeUserBranches holds the string denoting the user_branches edge name in mutations.
	EdgeUserBranches = "user_branches"
	// EdgeUserAccessPoints holds the string denoting the user_access_points edge name in mutations.
	EdgeUserAccessPoints = "user_access_points"
	// EdgeAttendanceDays holds the string denoting the attendance_days edge name in mutations.
	EdgeAttendanceDays = "attendance_days"
	// EdgeShiftAssignments holds the string denoting the shift_assignments edge name in mutations.
	EdgeShiftAssignments = "shift_assignments"
	// EdgeDayOverrides holds the string denoting the day_overrides edge name in mutations.
	EdgeDayOverrides = "day_overrides"
	// EdgeQrSessions holds the string denoting the qr_sessions edge name in mutations.
	EdgeQrSessions = "qr_sessions"
	// Table holds the table name of the user in the database.
	Table = "users"
	// RefreshTokensTable is the table that holds the refresh_tokens relation/edge.
	RefreshTokensTable = "refresh_tokens"
	// RefreshTokensInverseTable is the table name for the RefreshToken entity.
	// It exists in this package in order to avoid circular dependency with the "refreshtoken" package.
	RefreshTokensInverseTable = "refresh_tokens"
	// RefreshTokensColumn is the table column denoting the refresh_tokens relation/edge.
	RefreshTokensColumn = "user_refresh_tokens"
	// AddressesTable is the table that holds the addresses relation/edge.
	AddressesTable = "addresses"
	// AddressesInverseTable is the table name for the Address entity.
	// It exists in this package in order to avoid circular dependency with the "address" package.
	AddressesInverseTable = "addresses"
	// AddressesColumn is the table column denoting the addresses relation/edge.
	AddressesColumn = "user_addresses"
	// UserBranchesTable is the table that holds the user_branches relation/edge.
	UserBranchesTable = "user_branches"
	// UserBranchesInverseTable is the table name for the UserBranch entity.
	// It exists in this package in order to avoid circular dependency with the "userbranch" package.
	UserBranchesInverseTable = "user_branches"
	// UserBranchesColumn is the table column denoting the user_branches relation/edge.
	UserBranchesColumn = "user_id"
	// UserAccessPointsTable is the table that holds the user_access_points relation/edge.
	UserAccessPointsTable = "user_access_points"
	// UserAccessPointsInverseTable is the table name for the UserAccessPoint entity.
	// It exists in this package in order to avoid circular dependency with the "useraccesspoint" package.
	UserAccessPointsInverseTable = "user_access_points"
	// UserAccessPointsColumn is the table column denoting the user_access_points relation/edge.
	UserAccessPointsColumn = "user_id"
	// AttendanceDaysTable is the table that holds the attendance_days relation/edge.
	AttendanceDaysTable = "attendance_days"
	// AttendanceDaysInverseTable is the table name for the AttendanceDay entity.
	// It exists in this package in order to avoid circular dependency with the "attendanceday" package.
	AttendanceDaysInverseTable = "attendance_days"
	// AttendanceDaysColumn is the table column denoting the attendance_days relation/edge.
	AttendanceDaysColumn = "user_attendance_days"
	// ShiftAssignmentsTable is the table that holds the shift_assignments relation/edge.
	ShiftAssignmentsTable = "user_shift_assignments"
	// ShiftAssignmentsInverseTable is the table name for the UserShiftAssignment entity.
	// It exists in this package in order to avoid circular dependency with the "usershiftassignment" package.
	ShiftAssignmentsInverseTable = "user_shift_assignments"
	// ShiftAssignmentsColumn is the table column denoting the shift_assignments relation/edge.
	ShiftAssignmentsColumn = "user_id"
	// DayOverridesTable is the table that holds the day_overrides relation/edge.
	DayOverridesTable = "user_day_overrides"
	// DayOverridesInverseTable is the table name for the UserDayOverride entity.
	// It exists in this package in order to avoid circular dependency with the "userdayoverride" package.
	DayOverridesInverseTable = "user_day_overrides"
	// DayOverridesColumn is the table column denoting the day_overrides relation/edge.
	DayOverridesColumn = "user_id"
	// QrSessionsTable is the table that holds the qr_sessions relation/edge.
	QrSessionsTable = "user_qr_sessions"
	// QrSessionsInverseTable is the table name for the UserQRSession entity.
	// It exists in this package in order to avoid circular dependency with the "userqrsession" package.
	QrSessionsInverseTable = "user_qr_sessions"
	// QrSessionsColumn is the table column denoting the qr_sessions relation/edge.
	QrSessionsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPasswordHash,
	FieldRole,
	FieldIsActive,
	FieldFirstName,
	FieldLastName,
	FieldMiddleName,
	FieldEmail,
	FieldEmployeeCode,
	FieldAccessCode,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultRole holds the default value on creation for the "role" field.
	DefaultRole string
	// RoleValidator is a validator for the "role" field. It is called by the builders before save.
	RoleValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByMiddleName orders the results by the middle_name field.
func ByMiddleName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMiddleName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByEmployeeCode orders the results by the employee_code field.
func ByEmployeeCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmployeeCode, opts...).ToFunc()
}

// ByAccessCode orders the results by the access_code field.
func ByAccessCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessCode, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRefreshTokensCount orders the results by refresh_tokens count.
func ByRefreshTokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRefreshTokensStep(), opts...)
	}
}

// ByRefreshTokens orders the results by refresh_tokens terms.
func ByRefreshTokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRefreshTokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAddressesCount orders the results by addresses count.
func ByAddressesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAddressesStep(), opts...)
	}
}

// ByAddresses orders the results by addresses terms.
func ByAddresses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAddressesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserBranchesCount orders the results by user_branches count.
func ByUserBranchesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserBranchesStep(), opts...)
	}
}

// ByUserBranches orders the results by user_branches terms.
func ByUserBranches(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserBranchesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserAccessPointsCount orders the results by user_access_points count.
func ByUserAccessPointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUserAccessPointsStep(), opts...)
	}
}

// ByUserAccessPoints orders the results by user_access_points terms.
func ByUserAccessPoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserAccessPointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAttendanceDaysCount orders the results by attendance_days count.
func ByAttendanceDaysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAttendanceDaysStep(), opts...)
	}
}

// ByAttendanceDays orders the results by attendance_days terms.
func ByAttendanceDays(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAttendanceDaysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByShiftAssignmentsCount orders the results by shift_assignments count.
func ByShiftAssignmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newShiftAssignmentsStep(), opts...)
	}
}

// ByShiftAssignments orders the results by shift_assignments terms.
func ByShiftAssignments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShiftAssignmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDayOverridesCount orders the results by day_overrides count.
func ByDayOverridesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDayOverridesStep(), opts...)
	}
}

// ByDayOverrides orders the results by day_overrides terms.
func ByDayOverrides(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDayOverridesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByQrSessionsCount orders the results by qr_sessions count.
func ByQrSessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQrSessionsStep(), opts...)
	}
}

// ByQrSessions orders the results by qr_sessions terms.
func ByQrSessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQrSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newRefreshTokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RefreshTokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RefreshTokensTable, RefreshTokensColumn),
	)
}
func newAddressesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AddressesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AddressesTable, AddressesColumn),
	)
}
func newUserBranchesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserBranchesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserBranchesTable, UserBranchesColumn),
	)
}
func newUserAccessPointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserAccessPointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UserAccessPointsTable, UserAccessPointsColumn),
	)
}
func newAttendanceDaysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AttendanceDaysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AttendanceDaysTable, AttendanceDaysColumn),
	)
}
func newShiftAssignmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShiftAssignmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ShiftAssignmentsTable, ShiftAssignmentsColumn),
	)
}
func newDayOverridesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DayOverridesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DayOverridesTable, DayOverridesColumn),
	)
}
func newQrSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QrSessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QrSessionsTable, QrSessionsColumn),
	)
}
